# Predicting viability from image-based profiles using Elastic Net regression

## Imports, pathing, and constants

In [ ]:
import logging
import pathlib
import sys

import joblib
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns
import sklearn
import umap
from notebook_init_utils import bandicoot_check, init_notebook
from sklearn.linear_model import ElasticNetCV
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.model_selection import LeaveOneGroupOut, train_test_split
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler

root_dir, in_notebook = init_notebook()

profile_base_dir = bandicoot_check(
    pathlib.Path("/home/lippincm/mnt/bandicoot").resolve(), root_dir
)

/home/lippincm/Documents/NF1_organoid_profile_analysis/.venv/lib/python3.13/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [ ]:
# set up logging
year_month_day_hour_minute_log_name = (
    f"{pd.Timestamp.now().strftime('%Y-%m-%d_%H-%M')}_viability_prediction_training.log"
)
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s - %(levelname)s - %(message)s",
    handlers=[
        logging.FileHandler(f"../logs/{year_month_day_hour_minute_log_name}.log"),
        logging.StreamHandler(sys.stdout),
    ],
)

In [2]:
"""
Elastic Net viability model: 
training + evaluation under three split strategies

  1. "lopo"          - Leave-One-Patient-Out cross-validation
  2. "loto"          - Leave-One-Treatment-Out cross-validation
  3. "random_split"  - a single random 70/30 train/test split (no grouping)

All three reuse the same cleaning / training / metrics / artifact-saving
logic. For "lopo" and "loto", the model is refit once per fold (holding
out all rows for one patient / one treatment as the test set), metrics
are computed per fold, and results are aggregated across folds. For
"random_split", the model is fit once on a random 70% of rows and
evaluated on the held-out 30%, with the same metrics/artifact format so
it can be compared side-by-side with the grouped results.

Predicted viability is always bounded to [0, 100] before it's reported
or scored, since viability is a percentage and the raw ElasticNet
output is unconstrained and can fall outside that range.
"""

# ---------------------------------------------------------------------
# CONFIG - update these to match your data
# ---------------------------------------------------------------------
PATIENT_COL = "Metadata_Biology_PatientTumor"  # column identifying each patient
TREATMENT_COL = "Metadata_Experiment_FullTreatment"  # column identifying each treatment
SPLIT_COL = "Metadata_data_split"  # used only for split_method="predefined"

RANDOM_SPLIT_TEST_SIZE = 0.3  # fraction held out for the random_split test set
RANDOM_SPLIT_SEED = 0  # fixed seed so the random split is reproducible

VIABILITY_MIN = 0.0
VIABILITY_MAX = 100.0

MODEL_OUTPUT = pathlib.Path("../trained_models")
RESULTS_OUTPUT = pathlib.Path("../model_results")
MODEL_OUTPUT.mkdir(exist_ok=True)
RESULTS_OUTPUT.mkdir(exist_ok=True)


def clip_predictions(preds):
    """Bound predicted viability to a physically meaningful [0, 100] range."""
    return np.clip(preds, VIABILITY_MIN, VIABILITY_MAX)


# ---------------------------------------------------------------------
# Data cleaning (from your original script)
# ---------------------------------------------------------------------
def clean_features(df, feature_cols):
    """
    Reports inf/NaN diagnostics for feature_cols, then replaces inf with NaN,
    drops rows with NaN in those columns, and clips extreme values.
    Returns the cleaned dataframe (fewer rows if any contained inf/NaN).
    """
    X = df[feature_cols]

    print("Any inf in X:", np.isinf(X.values).any())
    print("Any NaN in X:", np.isnan(X.values).any())
    print("Max abs value in X:", np.nanmax(np.abs(X.values)))

    # Index into X's own columns, not df.columns — the boolean mask
    # has one entry per feature column, not per column in df.
    inf_mask = np.isinf(X.values).any(axis=0)
    inf_cols = X.columns[inf_mask]
    print("Columns with inf values:", list(inf_cols))

    # Option A: replace inf with NaN, then drop rows with NaN
    X = X.replace([np.inf, -np.inf], np.nan)
    valid_rows = X.dropna().index
    df = df.loc[valid_rows].copy()
    X = X.loc[valid_rows]

    # Option B: clip extreme values instead of dropping
    X = X.clip(lower=-1e10, upper=1e10)
    df[feature_cols] = X

    return df.reset_index(drop=True)


# ---------------------------------------------------------------------
# Model training (from your original script)
# ---------------------------------------------------------------------
def train_elastic_net(X_train: pd.DataFrame, Y_train: pd.Series) -> "Pipeline":
    elastic_net_model = make_pipeline(
        StandardScaler(),
        ElasticNetCV(
            l1_ratio=[0.1, 0.2, 0.5, 0.7, 0.9, 0.95, 0.99, 1.0],
            alphas=100,  # int -> auto-generates 100 alphas along the path
            cv=5,
            random_state=0,
            max_iter=50000,
            tol=1e-4,
            n_jobs=-1,
        ),
    )
    elastic_net_model.fit(X_train, Y_train.values.ravel())
    return elastic_net_model


# ---------------------------------------------------------------------
# Metrics (from your original script)
# ---------------------------------------------------------------------
def compute_metrics(model, X, Y) -> dict:
    y_pred = clip_predictions(model.predict(X))
    y_true = Y.values.ravel()
    r2 = r2_score(y_true, y_pred)
    mse = mean_squared_error(y_true, y_pred)
    mae = mean_absolute_error(y_true, y_pred)
    mape = np.mean(np.abs((y_true - y_pred) / y_true)) * 100
    rmse = np.sqrt(mse)
    return {"R2": r2, "MSE": mse, "MAE": mae, "MAPE": mape, "RMSE": rmse}


# ---------------------------------------------------------------------
# Strategy 1 & 2: grouped CV (LOPO / LOTO), reusing the same core logic
# ---------------------------------------------------------------------
def run_group_cv(
    viabilities_df: pd.DataFrame,
    feature_cols: list,
    viability_col: str,
    group_col: str,
    split_name: str,
    **kwargs,
) -> pd.DataFrame:
    """
    Runs Leave-One-Group-Out CV (group_col = patient or treatment column),
    refitting the elastic net pipeline each fold, and saving per-fold and
    aggregated artifacts under OUTPUT_DIR.
    """
    list_of_metadatas = []

    if "shuffle_status" in kwargs:
        shuffle_status = kwargs["shuffle_status"]
        list_of_metadatas.append(shuffle_status)
    else:
        shuffle_status = "not_shuffled"
    if "profile_type" in kwargs:
        profile_type = kwargs["profile_type"]
        list_of_metadatas.append(profile_type)
    tag = "__".join(list_of_metadatas) if list_of_metadatas else split_name

    # Clean BEFORE computing groups, so groups/train_idx/test_idx all line
    # up with the same (possibly row-dropped) dataframe.
    viabilities_df = clean_features(viabilities_df, feature_cols)
    groups = viabilities_df[group_col].values

    logo = LeaveOneGroupOut()

    all_metrics = []
    all_predictions = []
    all_importances = []

    n_splits = logo.get_n_splits(groups=groups)
    print(
        f"\n=== {split_name} grouped CV on '{group_col}' ({n_splits} folds) for {shuffle_status} ==="
    )

    for fold_idx, (train_idx, test_idx) in enumerate(
        logo.split(viabilities_df, groups=groups)
    ):
        held_out = np.unique(groups[test_idx])[0]

        train_df = viabilities_df.iloc[train_idx]
        test_df = viabilities_df.iloc[test_idx]

        X_train, X_test = train_df[feature_cols], test_df[feature_cols]
        Y_train, Y_test = train_df[viability_col], test_df[viability_col]

        # call custom training function to fit the model
        model = train_elastic_net(X_train, Y_train)

        for eval_split, (X_eval, Y_eval) in {
            "train": (X_train, Y_train),
            "test": (X_test, Y_test),
        }.items():
            m = compute_metrics(model, X_eval, Y_eval)
            m.update(
                {
                    "Metadata_fold": fold_idx,
                    "Metadata_held_out_group": held_out,
                    "Metadata_eval_split": eval_split,
                    "Metadata_n_samples": len(X_eval),
                }
            )
            all_metrics.append(m)

            print(
                f"  Fold {fold_idx} (held out={held_out}, n={len(X_eval)}, {eval_split}): "
                f"R2={m['R2']:.4f}, RMSE={m['RMSE']:.4f}"
            )

        # Everything below runs once per FOLD (not once per eval_split) -
        # the model/predictions/coefficients don't change between the
        # train-eval and test-eval passes above.

        # Held-out predictions (bounded to [0, 100] since viability is a percentage)
        fold_preds = test_df.copy()
        fold_preds["Actual_Viability"] = Y_test.values
        fold_preds["Predicted_Viability"] = clip_predictions(model.predict(X_test))
        fold_preds["Metadata_fold"] = fold_idx
        fold_preds["Metadata_held_out_group"] = held_out
        all_predictions.append(fold_preds)

        # Feature importances for this fold
        fold_importance = pd.DataFrame(
            {
                "feature": feature_cols,
                "importance": model.named_steps["elasticnetcv"].coef_,
                "Metadata_fold": fold_idx,
                "Metadata_held_out_group": held_out,
                "Metadata_shuffle_status": shuffle_status,
            }
        )
        all_importances.append(fold_importance)

        # Save the fold model (comment out if this produces too many files)
        joblib.dump(
            model,
            MODEL_OUTPUT
            / f"{split_name}_model_fold{fold_idx}_{held_out}__{tag}.joblib",
        )

    metrics_df = pd.DataFrame(all_metrics)[
        [
            "Metadata_fold",
            "Metadata_held_out_group",
            "Metadata_eval_split",
            "Metadata_n_samples",
            "R2",
            "MSE",
            "MAE",
            "MAPE",
            "RMSE",
        ]
    ]
    metrics_df.to_parquet(
        RESULTS_OUTPUT / f"{split_name}_model_performance__{tag}.parquet", index=False
    )

    predictions_df = pd.concat(all_predictions, ignore_index=True)
    predictions_df.to_parquet(
        RESULTS_OUTPUT / f"{split_name}_predicted_viabilities__{tag}.parquet",
        index=False,
    )

    importances_df = pd.concat(all_importances, ignore_index=True)
    importances_df.to_parquet(
        RESULTS_OUTPUT / f"{split_name}_feature_importances__{tag}.parquet", index=False
    )

    # Aggregate summary (mean/std across folds, test set only)
    test_metrics = metrics_df[metrics_df["Metadata_eval_split"] == "test"]
    summary = test_metrics[["R2", "MSE", "MAE", "MAPE", "RMSE"]].agg(["mean", "std"])
    print(f"\n--- {split_name} summary (across {n_splits} folds, test set) ---")
    print(summary)
    summary.to_parquet(RESULTS_OUTPUT / f"{split_name}_summary_metrics__{tag}.parquet")

    return metrics_df


# ---------------------------------------------------------------------
# Strategy 3: single random 70/30 train/test split (no grouping)
# ---------------------------------------------------------------------
def run_random_split(
    viabilities_df: pd.DataFrame,
    feature_cols: list,
    viability_col: str,
    split_name: str = "random_split",
    test_size: float = RANDOM_SPLIT_TEST_SIZE,
    random_state: int = RANDOM_SPLIT_SEED,
    **kwargs,
) -> pd.DataFrame:
    """
    Trains once on a random (test_size fraction) held-out split rather than
    grouping by patient or treatment. Rows are shuffled and split
    independently of any Metadata_* grouping column, so the same
    patient/treatment can appear in both train and test — this is meant as
    a baseline to compare against the stricter LOPO/LOTO splits, not a
    substitute for them.

    Saves the same artifact shapes (metrics/predictions/importances/model)
    as run_group_cv, using "Metadata_fold" = 0 and a fixed
    "Metadata_held_out_group" label, so results from both strategies can be
    concatenated and compared directly.
    """
    list_of_metadatas = []

    if "shuffle_status" in kwargs:
        shuffle_status = kwargs["shuffle_status"]
        list_of_metadatas.append(shuffle_status)
    else:
        shuffle_status = "not_shuffled"
    if "profile_type" in kwargs:
        profile_type = kwargs["profile_type"]
        list_of_metadatas.append(profile_type)
    tag = "__".join(list_of_metadatas) if list_of_metadatas else split_name

    viabilities_df = clean_features(viabilities_df, feature_cols)

    held_out_label = f"random_{int(round(test_size * 100))}pct_holdout"

    train_df, test_df = train_test_split(
        viabilities_df, test_size=test_size, random_state=random_state
    )

    print(
        f"\n=== {split_name} ({int(round((1 - test_size) * 100))}/{int(round(test_size * 100))} "
        f"train/test, n_train={len(train_df)}, n_test={len(test_df)}) for {shuffle_status} ==="
    )

    X_train, X_test = train_df[feature_cols], test_df[feature_cols]
    Y_train, Y_test = train_df[viability_col], test_df[viability_col]

    model = train_elastic_net(X_train, Y_train)

    all_metrics = []
    for eval_split, (X_eval, Y_eval) in {
        "train": (X_train, Y_train),
        "test": (X_test, Y_test),
    }.items():
        m = compute_metrics(model, X_eval, Y_eval)
        m.update(
            {
                "Metadata_fold": 0,
                "Metadata_held_out_group": held_out_label,
                "Metadata_eval_split": eval_split,
                "Metadata_n_samples": len(X_eval),
            }
        )
        all_metrics.append(m)
        print(
            f"  {eval_split} (n={len(X_eval)}): R2={m['R2']:.4f}, RMSE={m['RMSE']:.4f}"
        )

    # Held-out predictions (bounded to [0, 100] since viability is a percentage)
    fold_preds = test_df.copy()
    fold_preds["Actual_Viability"] = Y_test.values
    fold_preds["Predicted_Viability"] = clip_predictions(model.predict(X_test))
    fold_preds["Metadata_fold"] = 0
    fold_preds["Metadata_held_out_group"] = held_out_label

    fold_importance = pd.DataFrame(
        {
            "feature": feature_cols,
            "importance": model.named_steps["elasticnetcv"].coef_,
            "Metadata_fold": 0,
            "Metadata_held_out_group": held_out_label,
            "Metadata_shuffle_status": shuffle_status,
        }
    )

    joblib.dump(model, MODEL_OUTPUT / f"{split_name}_model__{tag}.joblib")

    metrics_df = pd.DataFrame(all_metrics)[
        [
            "Metadata_fold",
            "Metadata_held_out_group",
            "Metadata_eval_split",
            "Metadata_n_samples",
            "R2",
            "MSE",
            "MAE",
            "MAPE",
            "RMSE",
        ]
    ]
    metrics_df.to_parquet(
        RESULTS_OUTPUT / f"{split_name}_model_performance__{tag}.parquet", index=False
    )
    fold_preds.to_parquet(
        RESULTS_OUTPUT / f"{split_name}_predicted_viabilities__{tag}.parquet",
        index=False,
    )
    fold_importance.to_parquet(
        RESULTS_OUTPUT / f"{split_name}_feature_importances__{tag}.parquet", index=False
    )

    # Single-split summary (std will be NaN with only one test evaluation - that's expected)
    test_metrics = metrics_df[metrics_df["Metadata_eval_split"] == "test"]
    summary = test_metrics[["R2", "MSE", "MAE", "MAPE", "RMSE"]].agg(["mean", "std"])
    print(f"\n--- {split_name} summary (single split, test set) ---")
    print(summary)
    summary.to_parquet(RESULTS_OUTPUT / f"{split_name}_summary_metrics__{tag}.parquet")

    return metrics_df

In [3]:
patient_ids = pd.read_csv(
    pathlib.Path(f"{root_dir}/data/patient_IDs.txt").resolve(strict=True),
    header=None,
    sep="\t",
    names=["patient_id"],
)["patient_id"].to_list()

viabilities_path = pathlib.Path(f"{root_dir}/data/viabilities/").resolve(strict=True)

## Combine the profiles, viabilities, and platemap information

In [4]:
platemap_df_list = []
for patient in patient_ids:
    platemap_file_path = pathlib.Path(
        f"{root_dir}/config/platemaps/{patient}_platemap.csv"
    ).resolve(strict=True)
    tmp_df = pd.read_csv(platemap_file_path, index_col=0)
    tmp_df["patient_id"] = patient
    platemap_df_list.append(tmp_df)
platemap_df = pd.concat(platemap_df_list, axis=0)

In [5]:
viabilities_df_list = []
for patient in patient_ids:
    viabilities_file_path = pathlib.Path(
        f"{root_dir}/data/viabilities/{patient}_Viabilities.csv"
    ).resolve()
    if not viabilities_file_path.exists():
        continue
    viabilities_df = pd.read_csv(viabilities_file_path)
    # change DMSO dose to 1
    viabilities_df.loc[viabilities_df["Drug"] == "DMSO", "Concentration_uM"] = 1
    viabilities_df.loc[viabilities_df["Drug"] == "PD0325901", "Drug"] = "Mirdametinib"
    viabilities_df["patient_id"] = patient

    viabilities_df_list.append(viabilities_df)
viabilities_df = pd.concat(viabilities_df_list, axis=0)

In [6]:
# merge the viabilities with the platemap
platemap_viability_df = pd.merge(
    platemap_df,
    viabilities_df,
    how="left",
    left_on=["Treatment", "Dose", "patient_id"],
    right_on=["Drug", "Concentration_uM", "patient_id"],
).drop(columns=["WellCol", "WellPosition"])
# check if the NANs are in B wells only
nan_rows = platemap_viability_df[platemap_viability_df.isna().any(axis=1)]
# drop nan rows
platemap_viability_df = platemap_viability_df.dropna().reset_index(drop=True)
platemap_viability_df

,Treatment,Dose,Unit,patient_id,Drug,Concentration_uM,Viability_percentage
0,Staurosporine,10,nM,NF0014_T1,Staurosporine,10.0,5.515339
1,Digoxin,1,uM,NF0014_T1,Digoxin,1.0,22.499116
2,Digoxin,1,uM,NF0014_T1,Digoxin,1.0,22.499116
3,Onalespib,1,uM,NF0014_T1,Onalespib,1.0,32.645151
4,Staurosporine,10,nM,NF0014_T1,Staurosporine,10.0,5.515339
...,...,...,...,...,...,...,...
365,Staurosporine,10,nM,NF0055_T1,Staurosporine,10.0,4.276642
366,Selumetinib,1,uM,NF0055_T1,Selumetinib,1.0,108.513402
367,Selumetinib,10,uM,NF0055_T1,Selumetinib,10.0,108.783376
368,Selumetinib,10,uM,NF0055_T1,Selumetinib,10.0,108.783376
369,Staurosporine,10,nM,NF0055_T1,Staurosporine,10.0,4.276642

In [7]:
agg_profiles_path = pathlib.Path(
    f"{root_dir}/data/profiles_3D/all_patients/3.consensus_profiles/"
).resolve(strict=True)
agg_profiles_df_list = [x for x in agg_profiles_path.glob("*.parquet") if x.is_file()]

# Initialized ONCE, outside the per-profile loop, so results from every
# profile accumulate instead of being overwritten each iteration.
results = {
    "profile_type": [],
    "split_method": [],
    "shuffle_status": [],
    "results": [],
}

# Fixed seed so the "shuffled" permutation control is reproducible run-to-run.
rng = np.random.default_rng(0)

for consensus_path in agg_profiles_df_list:
    consensus_profile_name = consensus_path.stem
    print(f"Processing and training model for {consensus_profile_name}...")
    consensus_df = pd.read_parquet(consensus_path)

    viabilities_df = (
        pd.merge(
            consensus_df,
            platemap_viability_df,
            how="left",
            left_on=[
                "Metadata_Biology_PatientTumor",
                "Metadata_Experiment_Treatment",
                "Metadata_Experiment_Dose",
            ],
            right_on=["patient_id", "Treatment", "Dose"],
        )
        .drop(
            columns=[
                "Unit",
                "patient_id",
                "Drug",
                "Concentration_uM",
                "Treatment",
                "Dose",
            ]
        )
        .rename(
            columns={
                x: f"Metadata_{x}"
                for x in platemap_viability_df.columns
                if "Viability_percentage" not in x
                and x not in ["WellCol", "WellPosition", "Drug", "Concentration_uM"]
            }
        )
    )
    # drop NAN rows to avoid patients that do not have viability data
    viabilities_df = viabilities_df.dropna(subset=["Viability_percentage"]).reset_index(
        drop=True
    )
    # combine the two stratification columns into a single key
    viabilities_df["Metadata_Experiment_FullTreatment"] = (
        viabilities_df["Metadata_Experiment_Treatment"].astype(str)
        + "_"
        + viabilities_df["Metadata_Experiment_Dose"].astype(str)
    )
    viability_col = ["Viability_percentage"]
    metadata_cols = [
        col for col in viabilities_df.columns if col.startswith("Metadata_")
    ]
    feature_cols = [
        col
        for col in viabilities_df.columns
        if col not in metadata_cols and col not in viability_col
    ]
    viabilities_df[feature_cols] = viabilities_df[feature_cols].clip(
        lower=-1e10, upper=1e10
    )

    # down sample temporarily to speed up testing
    viabilities_df = viabilities_df.sample(n=24, random_state=0).reset_index(drop=True)

    for shuffle_status in ["not_shuffled", "shuffled"]:
        if shuffle_status == "shuffled":
            # permute the values in every column (fixed seed via rng, defined above)
            viabilities_df[feature_cols] = viabilities_df[feature_cols].apply(
                lambda col: rng.permutation(col.values)
            )
        for split_method in (
            "lopo",
            "loto",
            "random_split",
        ):
            if split_method == "lopo":
                group_col = PATIENT_COL
            elif split_method == "loto":
                group_col = TREATMENT_COL
            else:
                group_col = None  # not used for "random_split"

            if split_method == "random_split":
                fold_result = run_random_split(
                    viabilities_df,
                    feature_cols,
                    viability_col,
                    split_name=split_method,
                    test_size=RANDOM_SPLIT_TEST_SIZE,
                    random_state=RANDOM_SPLIT_SEED,
                    shuffle_status=shuffle_status,
                    profile_type=consensus_profile_name,
                )
            else:
                fold_result = run_group_cv(
                    viabilities_df,
                    feature_cols,
                    viability_col,
                    group_col=group_col,
                    split_name=split_method,
                    shuffle_status=shuffle_status,
                    profile_type=consensus_profile_name,
                )

            results["results"].append(fold_result)
            results["profile_type"].append(consensus_profile_name)
            results["split_method"].append(split_method)
            results["shuffle_status"].append(shuffle_status)

Processing and training model for nucleocentric_morphem_norm_sc_consensus_profiles...
Any inf in X: False
Any NaN in X: False
Max abs value in X: 4.414443435974015
Columns with inf values: []

=== lopo grouped CV on 'Metadata_Biology_PatientTumor' (6 folds) for not_shuffled ===
  Fold 0 (held out=NF0014_T1, n=21, train): R2=0.8400, RMSE=16.0634
  Fold 0 (held out=NF0014_T1, n=3, test): R2=0.6029, RMSE=19.0562
  Fold 1 (held out=NF0014_T2, n=21, train): R2=0.8727, RMSE=14.9343
  Fold 1 (held out=NF0014_T2, n=3, test): R2=-4.3773, RMSE=41.0576
  Fold 2 (held out=NF0018_T6, n=18, train): R2=0.8477, RMSE=17.1239
  Fold 2 (held out=NF0018_T6, n=6, test): R2=0.1693, RMSE=26.8559
  Fold 3 (held out=NF0035_T1, n=19, train): R2=0.7407, RMSE=19.3762
  Fold 3 (held out=NF0035_T1, n=5, test): R2=0.4428, RMSE=36.2688
  Fold 4 (held out=NF0037_T1, n=19, train): R2=0.8213, RMSE=17.6512
  Fold 4 (held out=NF0037_T1, n=5, test): R2=0.9426, RMSE=8.8470
  Fold 5 (held out=NF0055_T1, n=22, train): R2=0.8717, RMSE=13.9803
  Fold 5 (held out=NF0055_T1, n=2, test): R2=-0.5569, RMSE=68.3974

--- lopo summary (across 6 folds, test set) ---
            R2          MSE        MAE        MAPE       RMSE
mean -0.462779  1473.668468  25.572238  276.291622  33.413821
std   1.983057  1678.430753  16.810617  420.131210  20.703190
Any inf in X: False
Any NaN in X: False
Max abs value in X: 4.414443435974015
Columns with inf values: []

=== loto grouped CV on 'Metadata_Experiment_FullTreatment' (11 folds) for not_shuffled ===
  Fold 0 (held out=Binimetinib_1, n=22, train): R2=0.8191, RMSE=18.1023
  Fold 0 (held out=Binimetinib_1, n=2, test): R2=-61.8852, RMSE=7.9468
  Fold 1 (held out=Copanlisib_1, n=22, train): R2=0.7253, RMSE=22.1066
  Fold 1 (held out=Copanlisib_1, n=2, test): R2=-0.3937, RMSE=18.4438
  Fold 2 (held out=DMSO_1, n=20, train): R2=0.7707, RMSE=20.6409
  Fold 2 (held out=DMSO_1, n=4, test): R2=0.0000, RMSE=9.5923
  Fold 3 (held out=Everolimus_1, n=23, train): R2=0.8273, RMSE=17.3201
  Fold 3 (held out=Everolimus_1, n=1, test): R2=nan, RMSE=30.9581

/home/lippincm/Documents/NF1_organoid_profile_analysis/.venv/lib/python3.13/site-packages/sklearn/metrics/_regression.py:1295: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)

  Fold 4 (held out=Fimepinostat_1, n=23, train): R2=0.8657, RMSE=15.2939
  Fold 4 (held out=Fimepinostat_1, n=1, test): R2=nan, RMSE=58.1877

/home/lippincm/Documents/NF1_organoid_profile_analysis/.venv/lib/python3.13/site-packages/sklearn/metrics/_regression.py:1295: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)

  Fold 5 (held out=Linsitinib_1, n=23, train): R2=0.7522, RMSE=20.7816
  Fold 5 (held out=Linsitinib_1, n=1, test): R2=nan, RMSE=17.4728

/home/lippincm/Documents/NF1_organoid_profile_analysis/.venv/lib/python3.13/site-packages/sklearn/metrics/_regression.py:1295: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)

  Fold 6 (held out=Mirdametinib_1, n=22, train): R2=0.8045, RMSE=18.7805
  Fold 6 (held out=Mirdametinib_1, n=2, test): R2=0.0466, RMSE=6.4744
  Fold 7 (held out=Rapamycin_1, n=23, train): R2=0.7152, RMSE=21.8461
  Fold 7 (held out=Rapamycin_1, n=1, test): R2=nan, RMSE=13.9088

/home/lippincm/Documents/NF1_organoid_profile_analysis/.venv/lib/python3.13/site-packages/sklearn/metrics/_regression.py:1295: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)

  Fold 8 (held out=Selumetinib_1, n=23, train): R2=0.8028, RMSE=18.4483
  Fold 8 (held out=Selumetinib_1, n=1, test): R2=nan, RMSE=4.9738

/home/lippincm/Documents/NF1_organoid_profile_analysis/.venv/lib/python3.13/site-packages/sklearn/metrics/_regression.py:1295: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)

  Fold 9 (held out=Selumetinib_10, n=20, train): R2=0.8818, RMSE=13.0752
  Fold 9 (held out=Selumetinib_10, n=4, test): R2=-1.5614, RMSE=44.6705
  Fold 10 (held out=Staurosporine_10, n=19, train): R2=0.5555, RMSE=14.8847
  Fold 10 (held out=Staurosporine_10, n=5, test): R2=-9605.3962, RMSE=78.5088

--- loto summary (across 11 folds, test set) ---
               R2          MSE        MAE        MAPE       RMSE
mean -1611.531640  1233.094677  25.376607  152.326560  26.467066
std   3916.254913  1946.531036  23.496359  425.013673  24.204297
Any inf in X: False
Any NaN in X: False
Max abs value in X: 4.414443435974015
Columns with inf values: []

=== random_split (70/30 train/test, n_train=16, n_test=8) for not_shuffled ===
  train (n=16): R2=0.8522, RMSE=16.2130
  test (n=8): R2=0.4396, RMSE=28.0627

--- random_split summary (single split, test set) ---
            R2         MSE        MAE        MAPE       RMSE
mean  0.439592  787.517887  18.216818  101.564711  28.062749
std        NaN         NaN        NaN         NaN        NaN
Any inf in X: False
Any NaN in X: False
Max abs value in X: 4.414443435974015
Columns with inf values: []

=== lopo grouped CV on 'Metadata_Biology_PatientTumor' (6 folds) for shuffled ===
  Fold 0 (held out=NF0014_T1, n=21, train): R2=0.0163, RMSE=39.8255
  Fold 0 (held out=NF0014_T1, n=3, test): R2=-1.4786, RMSE=47.6085
  Fold 1 (held out=NF0014_T2, n=21, train): R2=0.0000, RMSE=41.8494
  Fold 1 (held out=NF0014_T2, n=3, test): R2=-2.8885, RMSE=34.9143
  Fold 2 (held out=NF0018_T6, n=18, train): R2=0.8783, RMSE=15.3097
  Fold 2 (held out=NF0018_T6, n=6, test): R2=-0.4250, RMSE=35.1732
  Fold 3 (held out=NF0035_T1, n=19, train): R2=0.0261, RMSE=37.5507
  Fold 3 (held out=NF0035_T1, n=5, test): R2=-0.0895, RMSE=50.7160
  Fold 4 (held out=NF0037_T1, n=19, train): R2=0.0000, RMSE=41.7519
  Fold 4 (held out=NF0037_T1, n=5, test): R2=-0.0298, RMSE=37.4630
  Fold 5 (held out=NF0055_T1, n=22, train): R2=0.0000, RMSE=39.0308
  Fold 5 (held out=NF0055_T1, n=2, test): R2=-0.1038, RMSE=57.5906

--- lopo summary (across 6 folds, test set) ---
            R2          MSE        MAE        MAPE       RMSE
mean -0.835851  2002.499831  36.159539  347.261615  43.910934
std   1.143504   857.869658  11.346695  290.692251   9.444346
Any inf in X: False
Any NaN in X: False
Max abs value in X: 4.414443435974015
Columns with inf values: []

=== loto grouped CV on 'Metadata_Experiment_FullTreatment' (11 folds) for shuffled ===
  Fold 0 (held out=Binimetinib_1, n=22, train): R2=0.0000, RMSE=42.5616
  Fold 0 (held out=Binimetinib_1, n=2, test): R2=-131.1856, RMSE=11.5215
  Fold 1 (held out=Copanlisib_1, n=22, train): R2=0.0000, RMSE=42.1804
  Fold 1 (held out=Copanlisib_1, n=2, test): R2=-1.0413, RMSE=22.3215
  Fold 2 (held out=DMSO_1, n=20, train): R2=0.0000, RMSE=43.1064
  Fold 2 (held out=DMSO_1, n=4, test): R2=0.0000, RMSE=29.6628
  Fold 3 (held out=Everolimus_1, n=23, train): R2=0.0000, RMSE=41.6773
  Fold 3 (held out=Everolimus_1, n=1, test): R2=nan, RMSE=12.3148

/home/lippincm/Documents/NF1_organoid_profile_analysis/.venv/lib/python3.13/site-packages/sklearn/metrics/_regression.py:1295: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)

  Fold 4 (held out=Fimepinostat_1, n=23, train): R2=0.0000, RMSE=41.7396
  Fold 4 (held out=Fimepinostat_1, n=1, test): R2=nan, RMSE=5.1783

/home/lippincm/Documents/NF1_organoid_profile_analysis/.venv/lib/python3.13/site-packages/sklearn/metrics/_regression.py:1295: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)

  Fold 5 (held out=Linsitinib_1, n=23, train): R2=0.0000, RMSE=41.7432
  Fold 5 (held out=Linsitinib_1, n=1, test): R2=nan, RMSE=4.4350

/home/lippincm/Documents/NF1_organoid_profile_analysis/.venv/lib/python3.13/site-packages/sklearn/metrics/_regression.py:1295: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)

  Fold 6 (held out=Mirdametinib_1, n=22, train): R2=0.0000, RMSE=42.4732
  Fold 6 (held out=Mirdametinib_1, n=2, test): R2=-3.9807, RMSE=14.7977
  Fold 7 (held out=Rapamycin_1, n=23, train): R2=0.0000, RMSE=40.9343
  Fold 7 (held out=Rapamycin_1, n=1, test): R2=nan, RMSE=40.3073

/home/lippincm/Documents/NF1_organoid_profile_analysis/.venv/lib/python3.13/site-packages/sklearn/metrics/_regression.py:1295: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)

  Fold 8 (held out=Selumetinib_1, n=23, train): R2=0.0000, RMSE=41.5407
  Fold 8 (held out=Selumetinib_1, n=1, test): R2=nan, RMSE=20.6037

/home/lippincm/Documents/NF1_organoid_profile_analysis/.venv/lib/python3.13/site-packages/sklearn/metrics/_regression.py:1295: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)

  Fold 9 (held out=Selumetinib_10, n=20, train): R2=0.0000, RMSE=38.0361
  Fold 9 (held out=Selumetinib_10, n=4, test): R2=-3.0980, RMSE=56.5029
  Fold 10 (held out=Staurosporine_10, n=19, train): R2=0.0016, RMSE=22.3064
  Fold 10 (held out=Staurosporine_10, n=5, test): R2=-12061.0705, RMSE=87.9729

--- loto summary (across 11 folds, test set) ---
               R2          MSE        MAE        MAPE       RMSE
mean -2033.396018  1355.361725  26.386179  164.687288  27.783473
std   4912.808997  2319.765914  24.863010  474.660213  25.333464
Any inf in X: False
Any NaN in X: False
Max abs value in X: 4.414443435974015
Columns with inf values: []

=== random_split (70/30 train/test, n_train=16, n_test=8) for shuffled ===
  train (n=16): R2=0.8522, RMSE=16.2126
  test (n=8): R2=-0.1197, RMSE=39.6670

--- random_split summary (single split, test set) ---
            R2          MSE        MAE        MAPE       RMSE
mean -0.119703  1573.470541  29.012365  294.519036  39.666996
std        NaN          NaN        NaN         NaN        NaN
Processing and training model for sammed_organoid_norm_sc_consensus_profiles...
Any inf in X: False
Any NaN in X: False
Max abs value in X: 6.624268628817648
Columns with inf values: []

=== lopo grouped CV on 'Metadata_Biology_PatientTumor' (6 folds) for not_shuffled ===
  Fold 0 (held out=NF0014_T1, n=21, train): R2=0.8758, RMSE=14.1498
  Fold 0 (held out=NF0014_T1, n=3, test): R2=-0.8765, RMSE=41.4249
  Fold 1 (held out=NF0014_T2, n=21, train): R2=0.8495, RMSE=16.2349
  Fold 1 (held out=NF0014_T2, n=3, test): R2=-2.2551, RMSE=31.9443
  Fold 2 (held out=NF0018_T6, n=18, train): R2=0.8787, RMSE=15.2836
  Fold 2 (held out=NF0018_T6, n=6, test): R2=-1.4687, RMSE=46.2955
  Fold 3 (held out=NF0035_T1, n=19, train): R2=0.9680, RMSE=6.8049
  Fold 3 (held out=NF0035_T1, n=5, test): R2=0.5197, RMSE=33.6740
  Fold 4 (held out=NF0037_T1, n=19, train): R2=0.8731, RMSE=14.8761
  Fold 4 (held out=NF0037_T1, n=5, test): R2=0.7667, RMSE=17.8310
  Fold 5 (held out=NF0055_T1, n=22, train): R2=0.7922, RMSE=17.7934
  Fold 5 (held out=NF0055_T1, n=2, test): R2=0.3630, RMSE=43.7514

--- lopo summary (across 6 folds, test set) ---
            R2          MSE        MAE        MAPE       RMSE
mean -0.491820  1374.300174  29.799656  223.232655  35.820181
std   1.228744   678.004380   9.232406  250.781760  10.462208
Any inf in X: False
Any NaN in X: False
Max abs value in X: 6.624268628817648
Columns with inf values: []

=== loto grouped CV on 'Metadata_Experiment_FullTreatment' (11 folds) for not_shuffled ===
  Fold 0 (held out=Binimetinib_1, n=22, train): R2=0.8945, RMSE=13.8249
  Fold 0 (held out=Binimetinib_1, n=2, test): R2=-3072.7272, RMSE=55.5583
  Fold 1 (held out=Copanlisib_1, n=22, train): R2=0.8912, RMSE=13.9104
  Fold 1 (held out=Copanlisib_1, n=2, test): R2=-6.3382, RMSE=42.3221
  Fold 2 (held out=DMSO_1, n=20, train): R2=0.8869, RMSE=14.4993
  Fold 2 (held out=DMSO_1, n=4, test): R2=0.0000, RMSE=11.7141
  Fold 3 (held out=Everolimus_1, n=23, train): R2=0.8946, RMSE=13.5296
  Fold 3 (held out=Everolimus_1, n=1, test): R2=nan, RMSE=24.0866

/home/lippincm/Documents/NF1_organoid_profile_analysis/.venv/lib/python3.13/site-packages/sklearn/metrics/_regression.py:1295: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)

  Fold 4 (held out=Fimepinostat_1, n=23, train): R2=0.8951, RMSE=13.5207
  Fold 4 (held out=Fimepinostat_1, n=1, test): R2=nan, RMSE=70.3185

/home/lippincm/Documents/NF1_organoid_profile_analysis/.venv/lib/python3.13/site-packages/sklearn/metrics/_regression.py:1295: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)

  Fold 5 (held out=Linsitinib_1, n=23, train): R2=0.8929, RMSE=13.6602
  Fold 5 (held out=Linsitinib_1, n=1, test): R2=nan, RMSE=10.2144

/home/lippincm/Documents/NF1_organoid_profile_analysis/.venv/lib/python3.13/site-packages/sklearn/metrics/_regression.py:1295: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)

  Fold 6 (held out=Mirdametinib_1, n=22, train): R2=0.8905, RMSE=14.0551
  Fold 6 (held out=Mirdametinib_1, n=2, test): R2=-4.2418, RMSE=15.1806
  Fold 7 (held out=Rapamycin_1, n=23, train): R2=0.8343, RMSE=16.6605
  Fold 7 (held out=Rapamycin_1, n=1, test): R2=nan, RMSE=18.2670

/home/lippincm/Documents/NF1_organoid_profile_analysis/.venv/lib/python3.13/site-packages/sklearn/metrics/_regression.py:1295: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)

  Fold 8 (held out=Selumetinib_1, n=23, train): R2=0.8886, RMSE=13.8664
  Fold 8 (held out=Selumetinib_1, n=1, test): R2=nan, RMSE=4.9738

/home/lippincm/Documents/NF1_organoid_profile_analysis/.venv/lib/python3.13/site-packages/sklearn/metrics/_regression.py:1295: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)

  Fold 9 (held out=Selumetinib_10, n=20, train): R2=0.9877, RMSE=4.2127
  Fold 9 (held out=Selumetinib_10, n=4, test): R2=-4.7647, RMSE=67.0149
  Fold 10 (held out=Staurosporine_10, n=19, train): R2=0.5559, RMSE=14.8778
  Fold 10 (held out=Staurosporine_10, n=5, test): R2=-9597.2423, RMSE=78.4755

--- loto summary (across 11 folds, test set) ---
               R2          MSE        MAE        MAPE       RMSE
mean -2114.219025  1989.324306  34.478105  163.373475  36.193260
std   3865.986542  2286.501501  26.574213  416.969900  27.336961
Any inf in X: False
Any NaN in X: False
Max abs value in X: 6.624268628817648
Columns with inf values: []

=== random_split (70/30 train/test, n_train=16, n_test=8) for not_shuffled ===
  train (n=16): R2=0.6247, RMSE=25.8361
  test (n=8): R2=0.2561, RMSE=32.3327

--- random_split summary (single split, test set) ---
            R2          MSE        MAE        MAPE       RMSE
mean  0.256075  1045.405879  23.388456  162.078763  32.332737
std        NaN          NaN        NaN         NaN        NaN
Any inf in X: False
Any NaN in X: False
Max abs value in X: 6.624268628817648
Columns with inf values: []

=== lopo grouped CV on 'Metadata_Biology_PatientTumor' (6 folds) for shuffled ===
  Fold 0 (held out=NF0014_T1, n=21, train): R2=0.0175, RMSE=39.8024
  Fold 0 (held out=NF0014_T1, n=3, test): R2=-1.4830, RMSE=47.6512
  Fold 1 (held out=NF0014_T2, n=21, train): R2=0.0023, RMSE=41.8010
  Fold 1 (held out=NF0014_T2, n=3, test): R2=-2.8938, RMSE=34.9378
  Fold 2 (held out=NF0018_T6, n=18, train): R2=0.2833, RMSE=37.1518
  Fold 2 (held out=NF0018_T6, n=6, test): R2=-0.1357, RMSE=31.4011
  Fold 3 (held out=NF0035_T1, n=19, train): R2=0.9719, RMSE=6.3765
  Fold 3 (held out=NF0035_T1, n=5, test): R2=-0.2096, RMSE=53.4374
  Fold 4 (held out=NF0037_T1, n=19, train): R2=0.8731, RMSE=14.8757
  Fold 4 (held out=NF0037_T1, n=5, test): R2=0.0620, RMSE=35.7554
  Fold 5 (held out=NF0055_T1, n=22, train): R2=0.0000, RMSE=39.0308
  Fold 5 (held out=NF0055_T1, n=2, test): R2=-0.1038, RMSE=57.5906

--- lopo summary (across 6 folds, test set) ---
            R2          MSE        MAE        MAPE       RMSE
mean -0.793977  1987.998241  36.106850  345.492577  43.462234
std   1.171977   968.932972  11.467335  292.520519  10.901327
Any inf in X: False
Any NaN in X: False
Max abs value in X: 6.624268628817648
Columns with inf values: []

=== loto grouped CV on 'Metadata_Experiment_FullTreatment' (11 folds) for shuffled ===
  Fold 0 (held out=Binimetinib_1, n=22, train): R2=0.0000, RMSE=42.5616
  Fold 0 (held out=Binimetinib_1, n=2, test): R2=-131.1856, RMSE=11.5215
  Fold 1 (held out=Copanlisib_1, n=22, train): R2=0.0000, RMSE=42.1804
  Fold 1 (held out=Copanlisib_1, n=2, test): R2=-1.0413, RMSE=22.3215
  Fold 2 (held out=DMSO_1, n=20, train): R2=0.8839, RMSE=14.6891
  Fold 2 (held out=DMSO_1, n=4, test): R2=0.0000, RMSE=42.8748
  Fold 3 (held out=Everolimus_1, n=23, train): R2=0.0000, RMSE=41.6773
  Fold 3 (held out=Everolimus_1, n=1, test): R2=nan, RMSE=12.3148

/home/lippincm/Documents/NF1_organoid_profile_analysis/.venv/lib/python3.13/site-packages/sklearn/metrics/_regression.py:1295: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)

  Fold 4 (held out=Fimepinostat_1, n=23, train): R2=0.0000, RMSE=41.7396
  Fold 4 (held out=Fimepinostat_1, n=1, test): R2=nan, RMSE=5.1783

/home/lippincm/Documents/NF1_organoid_profile_analysis/.venv/lib/python3.13/site-packages/sklearn/metrics/_regression.py:1295: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)

  Fold 5 (held out=Linsitinib_1, n=23, train): R2=0.0000, RMSE=41.7432
  Fold 5 (held out=Linsitinib_1, n=1, test): R2=nan, RMSE=4.4350

/home/lippincm/Documents/NF1_organoid_profile_analysis/.venv/lib/python3.13/site-packages/sklearn/metrics/_regression.py:1295: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)

  Fold 6 (held out=Mirdametinib_1, n=22, train): R2=0.0000, RMSE=42.4732
  Fold 6 (held out=Mirdametinib_1, n=2, test): R2=-3.9807, RMSE=14.7977
  Fold 7 (held out=Rapamycin_1, n=23, train): R2=0.0000, RMSE=40.9343
  Fold 7 (held out=Rapamycin_1, n=1, test): R2=nan, RMSE=40.3073

/home/lippincm/Documents/NF1_organoid_profile_analysis/.venv/lib/python3.13/site-packages/sklearn/metrics/_regression.py:1295: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)

  Fold 8 (held out=Selumetinib_1, n=23, train): R2=0.0000, RMSE=41.5407
  Fold 8 (held out=Selumetinib_1, n=1, test): R2=nan, RMSE=20.6037

/home/lippincm/Documents/NF1_organoid_profile_analysis/.venv/lib/python3.13/site-packages/sklearn/metrics/_regression.py:1295: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)

  Fold 9 (held out=Selumetinib_10, n=20, train): R2=0.9933, RMSE=3.1144
  Fold 9 (held out=Selumetinib_10, n=4, test): R2=-3.2165, RMSE=57.3137
  Fold 10 (held out=Staurosporine_10, n=19, train): R2=0.5560, RMSE=14.8757
  Fold 10 (held out=Staurosporine_10, n=5, test): R2=-11897.0658, RMSE=87.3728

--- loto summary (across 11 folds, test set) ---
               R2          MSE        MAE        MAPE       RMSE
mean -2006.081648  1441.309438  27.187564  164.349178  29.003720
std   4845.848330  2296.827032  24.996954  470.483543  25.692471
Any inf in X: False
Any NaN in X: False
Max abs value in X: 6.624268628817648
Columns with inf values: []

=== random_split (70/30 train/test, n_train=16, n_test=8) for shuffled ===
  train (n=16): R2=0.1967, RMSE=37.8013
  test (n=8): R2=-0.1680, RMSE=40.5137

--- random_split summary (single split, test set) ---
            R2          MSE        MAE       MAPE       RMSE
mean -0.168012  1641.358051  31.725014  300.59774  40.513677
std        NaN          NaN        NaN        NaN        NaN
Processing and training model for sc_norm_sc_consensus_profiles...
Any inf in X: False
Any NaN in X: False
Max abs value in X: 10000000000.0
Columns with inf values: []

=== lopo grouped CV on 'Metadata_Biology_PatientTumor' (6 folds) for not_shuffled ===
  Fold 0 (held out=NF0014_T1, n=21, train): R2=0.7405, RMSE=20.4543
  Fold 0 (held out=NF0014_T1, n=3, test): R2=0.0966, RMSE=28.7422

/home/lippincm/Documents/NF1_organoid_profile_analysis/.venv/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:840: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.722255e+00, tolerance: 3.678e+00
  model = cd_fast.enet_coordinate_descent(

  Fold 1 (held out=NF0014_T2, n=21, train): R2=0.9009, RMSE=13.1714
  Fold 1 (held out=NF0014_T2, n=3, test): R2=0.3754, RMSE=13.9936
  Fold 2 (held out=NF0018_T6, n=18, train): R2=0.8162, RMSE=18.8154
  Fold 2 (held out=NF0018_T6, n=6, test): R2=-5.6424, RMSE=75.9402
  Fold 3 (held out=NF0035_T1, n=19, train): R2=0.9719, RMSE=6.3771
  Fold 3 (held out=NF0035_T1, n=5, test): R2=-2.6278, RMSE=92.5442
  Fold 4 (held out=NF0037_T1, n=19, train): R2=0.6846, RMSE=23.4494
  Fold 4 (held out=NF0037_T1, n=5, test): R2=0.6568, RMSE=21.6268
  Fold 5 (held out=NF0055_T1, n=22, train): R2=0.8270, RMSE=16.2328
  Fold 5 (held out=NF0055_T1, n=2, test): R2=-0.5117, RMSE=67.3967

--- lopo summary (across 6 folds, test set) ---
            R2          MSE        MAE        MAPE       RMSE
mean -1.275514  3393.886036  42.046684  267.145109  50.040615
std   2.442300  3437.100022  28.797395  416.194984  32.677018
Any inf in X: False
Any NaN in X: False
Max abs value in X: 10000000000.0
Columns with inf values: []

=== loto grouped CV on 'Metadata_Experiment_FullTreatment' (11 folds) for not_shuffled ===
  Fold 0 (held out=Binimetinib_1, n=22, train): R2=0.7531, RMSE=21.1504
  Fold 0 (held out=Binimetinib_1, n=2, test): R2=-285.4915, RMSE=16.9618
  Fold 1 (held out=Copanlisib_1, n=22, train): R2=0.7409, RMSE=21.4693
  Fold 1 (held out=Copanlisib_1, n=2, test): R2=0.2103, RMSE=13.8841
  Fold 2 (held out=DMSO_1, n=20, train): R2=0.8071, RMSE=18.9321
  Fold 2 (held out=DMSO_1, n=4, test): R2=0.0000, RMSE=11.8439
  Fold 3 (held out=Everolimus_1, n=23, train): R2=0.8011, RMSE=18.5879
  Fold 3 (held out=Everolimus_1, n=1, test): R2=nan, RMSE=27.8617

/home/lippincm/Documents/NF1_organoid_profile_analysis/.venv/lib/python3.13/site-packages/sklearn/metrics/_regression.py:1295: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)

  Fold 4 (held out=Fimepinostat_1, n=23, train): R2=0.7612, RMSE=20.3955
  Fold 4 (held out=Fimepinostat_1, n=1, test): R2=nan, RMSE=29.6815

/home/lippincm/Documents/NF1_organoid_profile_analysis/.venv/lib/python3.13/site-packages/sklearn/metrics/_regression.py:1295: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)

  Fold 5 (held out=Linsitinib_1, n=23, train): R2=0.7578, RMSE=20.5445
  Fold 5 (held out=Linsitinib_1, n=1, test): R2=nan, RMSE=20.4688

/home/lippincm/Documents/NF1_organoid_profile_analysis/.venv/lib/python3.13/site-packages/sklearn/metrics/_regression.py:1295: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)

  Fold 6 (held out=Mirdametinib_1, n=22, train): R2=0.7734, RMSE=20.2190
  Fold 6 (held out=Mirdametinib_1, n=2, test): R2=0.1089, RMSE=6.2590
  Fold 7 (held out=Rapamycin_1, n=23, train): R2=0.7337, RMSE=21.1236
  Fold 7 (held out=Rapamycin_1, n=1, test): R2=nan, RMSE=13.9088

/home/lippincm/Documents/NF1_organoid_profile_analysis/.venv/lib/python3.13/site-packages/sklearn/metrics/_regression.py:1295: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)

  Fold 8 (held out=Selumetinib_1, n=23, train): R2=0.7905, RMSE=19.0130
  Fold 8 (held out=Selumetinib_1, n=1, test): R2=nan, RMSE=4.9738

/home/lippincm/Documents/NF1_organoid_profile_analysis/.venv/lib/python3.13/site-packages/sklearn/metrics/_regression.py:1295: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)

  Fold 9 (held out=Selumetinib_10, n=20, train): R2=0.9317, RMSE=9.9369
  Fold 9 (held out=Selumetinib_10, n=4, test): R2=-0.9932, RMSE=39.4058

/home/lippincm/Documents/NF1_organoid_profile_analysis/.venv/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:840: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.497311e+00, tolerance: 9.469e-01
  model = cd_fast.enet_coordinate_descent(

  Fold 10 (held out=Staurosporine_10, n=19, train): R2=0.5559, RMSE=14.8767
  Fold 10 (held out=Staurosporine_10, n=5, test): R2=-7317.3948, RMSE=68.5245

--- loto summary (across 11 folds, test set) ---
               R2          MSE        MAE        MAPE       RMSE
mean -1267.260061   836.616343  21.340607  120.856676  23.070330
std   2966.145122  1359.936466  15.649386  334.159289  18.297919
Any inf in X: False
Any NaN in X: False
Max abs value in X: 10000000000.0
Columns with inf values: []

=== random_split (70/30 train/test, n_train=16, n_test=8) for not_shuffled ===
  train (n=16): R2=0.8158, RMSE=18.1011
  test (n=8): R2=-0.6189, RMSE=47.6973

--- random_split summary (single split, test set) ---
            R2          MSE        MAE        MAPE       RMSE
mean -0.618945  2275.033975  33.295314  317.708411  47.697316
std        NaN          NaN        NaN         NaN        NaN
Any inf in X: False
Any NaN in X: False
Max abs value in X: 10000000000.0
Columns with inf values: []

=== lopo grouped CV on 'Metadata_Biology_PatientTumor' (6 folds) for shuffled ===
  Fold 0 (held out=NF0014_T1, n=21, train): R2=0.8756, RMSE=14.1606
  Fold 0 (held out=NF0014_T1, n=3, test): R2=-0.7560, RMSE=40.0731
  Fold 1 (held out=NF0014_T2, n=21, train): R2=0.8700, RMSE=15.0911
  Fold 1 (held out=NF0014_T2, n=3, test): R2=-0.8011, RMSE=23.7620
  Fold 2 (held out=NF0018_T6, n=18, train): R2=0.8786, RMSE=15.2894
  Fold 2 (held out=NF0018_T6, n=6, test): R2=-0.4888, RMSE=35.9517
  Fold 3 (held out=NF0035_T1, n=19, train): R2=0.8287, RMSE=15.7464
  Fold 3 (held out=NF0035_T1, n=5, test): R2=0.0998, RMSE=46.1003
  Fold 4 (held out=NF0037_T1, n=19, train): R2=0.8581, RMSE=15.7304
  Fold 4 (held out=NF0037_T1, n=5, test): R2=-0.3552, RMSE=42.9766
  Fold 5 (held out=NF0055_T1, n=22, train): R2=0.7991, RMSE=17.4956
  Fold 5 (held out=NF0055_T1, n=2, test): R2=0.1356, RMSE=50.9636

--- lopo summary (across 6 folds, test set) ---
            R2          MSE        MAE        MAPE       RMSE
mean -0.360950  1672.086462  31.007229  298.146559  39.971209
std   0.406223   702.400123  10.667158  235.163025   9.448108
Any inf in X: False
Any NaN in X: False
Max abs value in X: 10000000000.0
Columns with inf values: []

=== loto grouped CV on 'Metadata_Experiment_FullTreatment' (11 folds) for shuffled ===
  Fold 0 (held out=Binimetinib_1, n=22, train): R2=0.8043, RMSE=18.8284
  Fold 0 (held out=Binimetinib_1, n=2, test): R2=-245.7199, RMSE=15.7405
  Fold 1 (held out=Copanlisib_1, n=22, train): R2=0.8845, RMSE=14.3348
  Fold 1 (held out=Copanlisib_1, n=2, test): R2=-5.2569, RMSE=39.0797
  Fold 2 (held out=DMSO_1, n=20, train): R2=0.8867, RMSE=14.5067
  Fold 2 (held out=DMSO_1, n=4, test): R2=0.0000, RMSE=29.3294
  Fold 3 (held out=Everolimus_1, n=23, train): R2=0.8566, RMSE=15.7846
  Fold 3 (held out=Everolimus_1, n=1, test): R2=nan, RMSE=15.6549

/home/lippincm/Documents/NF1_organoid_profile_analysis/.venv/lib/python3.13/site-packages/sklearn/metrics/_regression.py:1295: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)

  Fold 4 (held out=Fimepinostat_1, n=23, train): R2=0.8312, RMSE=17.1474
  Fold 4 (held out=Fimepinostat_1, n=1, test): R2=nan, RMSE=4.3591

/home/lippincm/Documents/NF1_organoid_profile_analysis/.venv/lib/python3.13/site-packages/sklearn/metrics/_regression.py:1295: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)

  Fold 5 (held out=Linsitinib_1, n=23, train): R2=0.8569, RMSE=15.7894
  Fold 5 (held out=Linsitinib_1, n=1, test): R2=nan, RMSE=2.1666

/home/lippincm/Documents/NF1_organoid_profile_analysis/.venv/lib/python3.13/site-packages/sklearn/metrics/_regression.py:1295: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)

  Fold 6 (held out=Mirdametinib_1, n=22, train): R2=0.8877, RMSE=14.2312
  Fold 6 (held out=Mirdametinib_1, n=2, test): R2=-3.6068, RMSE=14.2314
  Fold 7 (held out=Rapamycin_1, n=23, train): R2=0.8721, RMSE=14.6389
  Fold 7 (held out=Rapamycin_1, n=1, test): R2=nan, RMSE=38.0888

/home/lippincm/Documents/NF1_organoid_profile_analysis/.venv/lib/python3.13/site-packages/sklearn/metrics/_regression.py:1295: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)

  Fold 8 (held out=Selumetinib_1, n=23, train): R2=0.8565, RMSE=15.7371
  Fold 8 (held out=Selumetinib_1, n=1, test): R2=nan, RMSE=11.6551

/home/lippincm/Documents/NF1_organoid_profile_analysis/.venv/lib/python3.13/site-packages/sklearn/metrics/_regression.py:1295: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)

  Fold 9 (held out=Selumetinib_10, n=20, train): R2=0.9932, RMSE=3.1414
  Fold 9 (held out=Selumetinib_10, n=4, test): R2=-2.8074, RMSE=54.4623
  Fold 10 (held out=Staurosporine_10, n=19, train): R2=0.5559, RMSE=14.8768
  Fold 10 (held out=Staurosporine_10, n=5, test): R2=-13035.5504, RMSE=91.4575

--- loto summary (across 11 folds, test set) ---
               R2          MSE        MAE        MAPE       RMSE
mean -2215.490230  1456.702568  26.241807  171.106985  28.747759
std   5301.615227  2465.342070  24.971076  492.605497  26.330511
Any inf in X: False
Any NaN in X: False
Max abs value in X: 10000000000.0
Columns with inf values: []

=== random_split (70/30 train/test, n_train=16, n_test=8) for shuffled ===
  train (n=16): R2=0.8517, RMSE=16.2411
  test (n=8): R2=0.1946, RMSE=33.6424

--- random_split summary (single split, test set) ---
            R2          MSE        MAE        MAPE       RMSE
mean  0.194587  1131.812942  16.349595  194.229384  33.642428
std        NaN          NaN        NaN         NaN        NaN
Processing and training model for organoid_norm_sc_consensus_profiles...
Any inf in X: False
Any NaN in X: False
Max abs value in X: 10000000000.0
Columns with inf values: []

=== lopo grouped CV on 'Metadata_Biology_PatientTumor' (6 folds) for not_shuffled ===
  Fold 0 (held out=NF0014_T1, n=21, train): R2=0.7662, RMSE=19.4168
  Fold 0 (held out=NF0014_T1, n=3, test): R2=-3.7216, RMSE=65.7100
  Fold 1 (held out=NF0014_T2, n=21, train): R2=0.7246, RMSE=21.9605
  Fold 1 (held out=NF0014_T2, n=3, test): R2=-2.9349, RMSE=35.1217
  Fold 2 (held out=NF0018_T6, n=18, train): R2=0.7359, RMSE=22.5518
  Fold 2 (held out=NF0018_T6, n=6, test): R2=-0.9158, RMSE=40.7837
  Fold 3 (held out=NF0035_T1, n=19, train): R2=0.7378, RMSE=19.4823
  Fold 3 (held out=NF0035_T1, n=5, test): R2=-1.2521, RMSE=72.9164
  Fold 4 (held out=NF0037_T1, n=19, train): R2=0.4804, RMSE=30.0965
  Fold 4 (held out=NF0037_T1, n=5, test): R2=0.4704, RMSE=26.8658
  Fold 5 (held out=NF0055_T1, n=22, train): R2=0.7522, RMSE=19.4279
  Fold 5 (held out=NF0055_T1, n=2, test): R2=-0.6103, RMSE=69.5603

--- lopo summary (across 6 folds, test set) ---
            R2          MSE        MAE        MAPE       RMSE
mean -1.494054  3015.311875  45.417021  370.147716  51.826339
std   1.553775  2028.834767  18.446813  427.644883  19.879914
Any inf in X: False
Any NaN in X: False
Max abs value in X: 10000000000.0
Columns with inf values: []

=== loto grouped CV on 'Metadata_Experiment_FullTreatment' (11 folds) for not_shuffled ===
  Fold 0 (held out=Binimetinib_1, n=22, train): R2=0.8178, RMSE=18.1662
  Fold 0 (held out=Binimetinib_1, n=2, test): R2=-757.0448, RMSE=27.5908
  Fold 1 (held out=Copanlisib_1, n=22, train): R2=0.6538, RMSE=24.8168
  Fold 1 (held out=Copanlisib_1, n=2, test): R2=-6.3382, RMSE=42.3221
  Fold 2 (held out=DMSO_1, n=20, train): R2=0.6709, RMSE=24.7275
  Fold 2 (held out=DMSO_1, n=4, test): R2=0.0000, RMSE=27.9947
  Fold 3 (held out=Everolimus_1, n=23, train): R2=0.6617, RMSE=24.2414
  Fold 3 (held out=Everolimus_1, n=1, test): R2=nan, RMSE=22.8774

/home/lippincm/Documents/NF1_organoid_profile_analysis/.venv/lib/python3.13/site-packages/sklearn/metrics/_regression.py:1295: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)

  Fold 4 (held out=Fimepinostat_1, n=23, train): R2=0.6301, RMSE=25.3875
  Fold 4 (held out=Fimepinostat_1, n=1, test): R2=nan, RMSE=70.3185

/home/lippincm/Documents/NF1_organoid_profile_analysis/.venv/lib/python3.13/site-packages/sklearn/metrics/_regression.py:1295: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)

  Fold 5 (held out=Linsitinib_1, n=23, train): R2=0.7712, RMSE=19.9677
  Fold 5 (held out=Linsitinib_1, n=1, test): R2=nan, RMSE=35.5733

/home/lippincm/Documents/NF1_organoid_profile_analysis/.venv/lib/python3.13/site-packages/sklearn/metrics/_regression.py:1295: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)

  Fold 6 (held out=Mirdametinib_1, n=22, train): R2=0.8025, RMSE=18.8755
  Fold 6 (held out=Mirdametinib_1, n=2, test): R2=-6.8343, RMSE=18.5588
  Fold 7 (held out=Rapamycin_1, n=23, train): R2=0.6770, RMSE=23.2628
  Fold 7 (held out=Rapamycin_1, n=1, test): R2=nan, RMSE=13.9088

/home/lippincm/Documents/NF1_organoid_profile_analysis/.venv/lib/python3.13/site-packages/sklearn/metrics/_regression.py:1295: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)

  Fold 8 (held out=Selumetinib_1, n=23, train): R2=0.6569, RMSE=24.3325
  Fold 8 (held out=Selumetinib_1, n=1, test): R2=nan, RMSE=4.9738

/home/lippincm/Documents/NF1_organoid_profile_analysis/.venv/lib/python3.13/site-packages/sklearn/metrics/_regression.py:1295: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)

  Fold 9 (held out=Selumetinib_10, n=20, train): R2=0.8319, RMSE=15.5968
  Fold 9 (held out=Selumetinib_10, n=4, test): R2=-2.6678, RMSE=53.4542
  Fold 10 (held out=Staurosporine_10, n=19, train): R2=0.5560, RMSE=14.8757
  Fold 10 (held out=Staurosporine_10, n=5, test): R2=-12395.2523, RMSE=89.1833

--- loto summary (across 11 folds, test set) ---
               R2          MSE        MAE        MAPE       RMSE
mean -2194.689564  1949.388913  35.694417  182.151869  36.977797
std   5006.306339  2459.831423  25.103652  478.629698  25.302857
Any inf in X: False
Any NaN in X: False
Max abs value in X: 10000000000.0
Columns with inf values: []

=== random_split (70/30 train/test, n_train=16, n_test=8) for not_shuffled ===
  train (n=16): R2=0.7596, RMSE=20.6805
  test (n=8): R2=-0.1411, RMSE=40.0450

--- random_split summary (single split, test set) ---
            R2          MSE        MAE        MAPE       RMSE
mean -0.141146  1603.604316  28.794769  218.208225  40.045029
std        NaN          NaN        NaN         NaN        NaN
Any inf in X: False
Any NaN in X: False
Max abs value in X: 10000000000.0
Columns with inf values: []

=== lopo grouped CV on 'Metadata_Biology_PatientTumor' (6 folds) for shuffled ===
  Fold 0 (held out=NF0014_T1, n=21, train): R2=0.7083, RMSE=21.6867
  Fold 0 (held out=NF0014_T1, n=3, test): R2=0.0966, RMSE=28.7422
  Fold 1 (held out=NF0014_T2, n=21, train): R2=0.0000, RMSE=41.8494
  Fold 1 (held out=NF0014_T2, n=3, test): R2=-2.8885, RMSE=34.9143
  Fold 2 (held out=NF0018_T6, n=18, train): R2=0.8787, RMSE=15.2834
  Fold 2 (held out=NF0018_T6, n=6, test): R2=-1.9474, RMSE=50.5860
  Fold 3 (held out=NF0035_T1, n=19, train): R2=0.1571, RMSE=34.9351
  Fold 3 (held out=NF0035_T1, n=5, test): R2=-0.4434, RMSE=58.3751
  Fold 4 (held out=NF0037_T1, n=19, train): R2=0.1022, RMSE=39.5619
  Fold 4 (held out=NF0037_T1, n=5, test): R2=-0.7212, RMSE=48.4339
  Fold 5 (held out=NF0055_T1, n=22, train): R2=0.1877, RMSE=35.1776
  Fold 5 (held out=NF0055_T1, n=2, test): R2=0.7382, RMSE=28.0455

--- lopo summary (across 6 folds, test set) ---
            R2          MSE        MAE       MAPE       RMSE
mean -0.860952  1857.351896  32.586272  93.636546  41.516164
std   1.338629  1072.553050   9.294040  90.739360  12.669335
Any inf in X: False
Any NaN in X: False
Max abs value in X: 10000000000.0
Columns with inf values: []

=== loto grouped CV on 'Metadata_Experiment_FullTreatment' (11 folds) for shuffled ===
  Fold 0 (held out=Binimetinib_1, n=22, train): R2=0.0000, RMSE=42.5616
  Fold 0 (held out=Binimetinib_1, n=2, test): R2=-131.1856, RMSE=11.5215
  Fold 1 (held out=Copanlisib_1, n=22, train): R2=0.0000, RMSE=42.1804
  Fold 1 (held out=Copanlisib_1, n=2, test): R2=-1.0413, RMSE=22.3215
  Fold 2 (held out=DMSO_1, n=20, train): R2=0.2307, RMSE=37.8077
  Fold 2 (held out=DMSO_1, n=4, test): R2=0.0000, RMSE=52.8432
  Fold 3 (held out=Everolimus_1, n=23, train): R2=0.0000, RMSE=41.6773
  Fold 3 (held out=Everolimus_1, n=1, test): R2=nan, RMSE=12.3148

/home/lippincm/Documents/NF1_organoid_profile_analysis/.venv/lib/python3.13/site-packages/sklearn/metrics/_regression.py:1295: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)

  Fold 4 (held out=Fimepinostat_1, n=23, train): R2=0.0000, RMSE=41.7396
  Fold 4 (held out=Fimepinostat_1, n=1, test): R2=nan, RMSE=5.1783

/home/lippincm/Documents/NF1_organoid_profile_analysis/.venv/lib/python3.13/site-packages/sklearn/metrics/_regression.py:1295: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)

  Fold 5 (held out=Linsitinib_1, n=23, train): R2=0.6763, RMSE=23.7511
  Fold 5 (held out=Linsitinib_1, n=1, test): R2=nan, RMSE=20.4688

/home/lippincm/Documents/NF1_organoid_profile_analysis/.venv/lib/python3.13/site-packages/sklearn/metrics/_regression.py:1295: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)

  Fold 6 (held out=Mirdametinib_1, n=22, train): R2=0.0000, RMSE=42.4732
  Fold 6 (held out=Mirdametinib_1, n=2, test): R2=-3.9807, RMSE=14.7977
  Fold 7 (held out=Rapamycin_1, n=23, train): R2=0.0000, RMSE=40.9343
  Fold 7 (held out=Rapamycin_1, n=1, test): R2=nan, RMSE=40.3073

/home/lippincm/Documents/NF1_organoid_profile_analysis/.venv/lib/python3.13/site-packages/sklearn/metrics/_regression.py:1295: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)

  Fold 8 (held out=Selumetinib_1, n=23, train): R2=0.0004, RMSE=41.5314
  Fold 8 (held out=Selumetinib_1, n=1, test): R2=nan, RMSE=20.6110

/home/lippincm/Documents/NF1_organoid_profile_analysis/.venv/lib/python3.13/site-packages/sklearn/metrics/_regression.py:1295: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)

  Fold 9 (held out=Selumetinib_10, n=20, train): R2=0.0000, RMSE=38.0361
  Fold 9 (held out=Selumetinib_10, n=4, test): R2=-3.0980, RMSE=56.5029
  Fold 10 (held out=Staurosporine_10, n=19, train): R2=0.4420, RMSE=16.6765
  Fold 10 (held out=Staurosporine_10, n=5, test): R2=-5593.2237, RMSE=59.9112

--- loto summary (across 11 folds, test set) ---
               R2          MSE        MAE       MAPE       RMSE
mean  -955.421552  1188.292867  24.040077   89.38936  28.797998
std   2272.637471  1366.534649  14.689719  216.73623  19.871210
Any inf in X: False
Any NaN in X: False
Max abs value in X: 10000000000.0
Columns with inf values: []

=== random_split (70/30 train/test, n_train=16, n_test=8) for shuffled ===
  train (n=16): R2=0.8523, RMSE=16.2106
  test (n=8): R2=0.8902, RMSE=12.4221

--- random_split summary (single split, test set) ---
            R2        MSE       MAE       MAPE       RMSE
mean  0.890192  154.30864  8.666959  34.002816  12.422103
std        NaN        NaN       NaN        NaN        NaN
Processing and training model for sammed_nucleocentric_norm_sc_consensus_profiles...
Any inf in X: False
Any NaN in X: False
Max abs value in X: 1.7037208758706792
Columns with inf values: []

=== lopo grouped CV on 'Metadata_Biology_PatientTumor' (6 folds) for not_shuffled ===
  Fold 0 (held out=NF0014_T1, n=21, train): R2=0.8755, RMSE=14.1677
  Fold 0 (held out=NF0014_T1, n=3, test): R2=-0.7081, RMSE=39.5222
  Fold 1 (held out=NF0014_T2, n=21, train): R2=0.8735, RMSE=14.8821
  Fold 1 (held out=NF0014_T2, n=3, test): R2=-5.5626, RMSE=45.3574
  Fold 2 (held out=NF0018_T6, n=18, train): R2=0.7915, RMSE=20.0398
  Fold 2 (held out=NF0018_T6, n=6, test): R2=-0.0330, RMSE=29.9477
  Fold 3 (held out=NF0035_T1, n=19, train): R2=0.8241, RMSE=15.9598
  Fold 3 (held out=NF0035_T1, n=5, test): R2=0.5756, RMSE=31.6535
  Fold 4 (held out=NF0037_T1, n=19, train): R2=0.8731, RMSE=14.8759
  Fold 4 (held out=NF0037_T1, n=5, test): R2=0.9960, RMSE=2.3394
  Fold 5 (held out=NF0055_T1, n=22, train): R2=0.8650, RMSE=14.3409
  Fold 5 (held out=NF0055_T1, n=2, test): R2=0.1948, RMSE=49.1878

--- lopo summary (across 6 folds, test set) ---
            R2          MSE        MAE        MAPE       RMSE
mean -0.756215  1323.835450  27.309586  246.414429  33.001330
std   2.423823   873.958612  14.470400  308.096845  16.783838
Any inf in X: False
Any NaN in X: False
Max abs value in X: 1.7037208758706792
Columns with inf values: []

=== loto grouped CV on 'Metadata_Experiment_FullTreatment' (11 folds) for not_shuffled ===
  Fold 0 (held out=Binimetinib_1, n=22, train): R2=0.8945, RMSE=13.8246
  Fold 0 (held out=Binimetinib_1, n=2, test): R2=-200.5810, RMSE=14.2279
  Fold 1 (held out=Copanlisib_1, n=22, train): R2=0.7397, RMSE=21.5184
  Fold 1 (held out=Copanlisib_1, n=2, test): R2=-0.5184, RMSE=19.2517
  Fold 2 (held out=DMSO_1, n=20, train): R2=0.7404, RMSE=21.9645
  Fold 2 (held out=DMSO_1, n=4, test): R2=0.0000, RMSE=9.1669
  Fold 3 (held out=Everolimus_1, n=23, train): R2=0.8436, RMSE=16.4818
  Fold 3 (held out=Everolimus_1, n=1, test): R2=nan, RMSE=31.3389

/home/lippincm/Documents/NF1_organoid_profile_analysis/.venv/lib/python3.13/site-packages/sklearn/metrics/_regression.py:1295: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)

  Fold 4 (held out=Fimepinostat_1, n=23, train): R2=0.8789, RMSE=14.5281
  Fold 4 (held out=Fimepinostat_1, n=1, test): R2=nan, RMSE=62.8010

/home/lippincm/Documents/NF1_organoid_profile_analysis/.venv/lib/python3.13/site-packages/sklearn/metrics/_regression.py:1295: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)

  Fold 5 (held out=Linsitinib_1, n=23, train): R2=0.8722, RMSE=14.9227
  Fold 5 (held out=Linsitinib_1, n=1, test): R2=nan, RMSE=13.9031

/home/lippincm/Documents/NF1_organoid_profile_analysis/.venv/lib/python3.13/site-packages/sklearn/metrics/_regression.py:1295: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)

  Fold 6 (held out=Mirdametinib_1, n=22, train): R2=0.8671, RMSE=15.4825
  Fold 6 (held out=Mirdametinib_1, n=2, test): R2=-10.3556, RMSE=22.3437
  Fold 7 (held out=Rapamycin_1, n=23, train): R2=0.8708, RMSE=14.7143
  Fold 7 (held out=Rapamycin_1, n=1, test): R2=nan, RMSE=13.9088

/home/lippincm/Documents/NF1_organoid_profile_analysis/.venv/lib/python3.13/site-packages/sklearn/metrics/_regression.py:1295: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)

  Fold 8 (held out=Selumetinib_1, n=23, train): R2=0.7649, RMSE=20.1434
  Fold 8 (held out=Selumetinib_1, n=1, test): R2=nan, RMSE=2.5127

/home/lippincm/Documents/NF1_organoid_profile_analysis/.venv/lib/python3.13/site-packages/sklearn/metrics/_regression.py:1295: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)

  Fold 9 (held out=Selumetinib_10, n=20, train): R2=0.8024, RMSE=16.9079
  Fold 9 (held out=Selumetinib_10, n=4, test): R2=-1.0647, RMSE=40.1065
  Fold 10 (held out=Staurosporine_10, n=19, train): R2=0.5560, RMSE=14.8759
  Fold 10 (held out=Staurosporine_10, n=5, test): R2=-8902.1099, RMSE=75.5804

--- loto summary (across 11 folds, test set) ---
               R2          MSE        MAE        MAPE       RMSE
mean -1519.104953  1254.219085  26.636795  149.006433  27.740145
std   3617.784503  1869.330521  22.664295  406.657724  23.090557
Any inf in X: False
Any NaN in X: False
Max abs value in X: 1.7037208758706792
Columns with inf values: []

=== random_split (70/30 train/test, n_train=16, n_test=8) for not_shuffled ===
  train (n=16): R2=0.7657, RMSE=20.4138
  test (n=8): R2=0.2500, RMSE=32.4637

--- random_split summary (single split, test set) ---
            R2          MSE        MAE        MAPE       RMSE
mean  0.250038  1053.889618  23.625982  153.929646  32.463666
std        NaN          NaN        NaN         NaN        NaN
Any inf in X: False
Any NaN in X: False
Max abs value in X: 1.7037208758706792
Columns with inf values: []

=== lopo grouped CV on 'Metadata_Biology_PatientTumor' (6 folds) for shuffled ===
  Fold 0 (held out=NF0014_T1, n=21, train): R2=0.8758, RMSE=14.1509
  Fold 0 (held out=NF0014_T1, n=3, test): R2=-0.8493, RMSE=41.1235
  Fold 1 (held out=NF0014_T2, n=21, train): R2=0.8151, RMSE=17.9971
  Fold 1 (held out=NF0014_T2, n=3, test): R2=-3.6493, RMSE=38.1774
  Fold 2 (held out=NF0018_T6, n=18, train): R2=0.8787, RMSE=15.2856
  Fold 2 (held out=NF0018_T6, n=6, test): R2=-0.1282, RMSE=31.2962
  Fold 3 (held out=NF0035_T1, n=19, train): R2=0.9719, RMSE=6.3758
  Fold 3 (held out=NF0035_T1, n=5, test): R2=-0.0184, RMSE=49.0321
  Fold 4 (held out=NF0037_T1, n=19, train): R2=0.8724, RMSE=14.9149
  Fold 4 (held out=NF0037_T1, n=5, test): R2=0.1914, RMSE=33.1962
  Fold 5 (held out=NF0055_T1, n=22, train): R2=0.8803, RMSE=13.5037
  Fold 5 (held out=NF0055_T1, n=2, test): R2=-0.2164, RMSE=60.4571

--- lopo summary (across 6 folds, test set) ---
            R2          MSE        MAE        MAPE       RMSE
mean -0.778351  1881.551234  33.806179  337.631007  42.213758
std   1.449424  1005.585063  12.778289  309.521272  10.929770
Any inf in X: False
Any NaN in X: False
Max abs value in X: 1.7037208758706792
Columns with inf values: []

=== loto grouped CV on 'Metadata_Experiment_FullTreatment' (11 folds) for shuffled ===
  Fold 0 (held out=Binimetinib_1, n=22, train): R2=0.8551, RMSE=16.1996
  Fold 0 (held out=Binimetinib_1, n=2, test): R2=-79.0632, RMSE=8.9667
  Fold 1 (held out=Copanlisib_1, n=22, train): R2=0.8926, RMSE=13.8244
  Fold 1 (held out=Copanlisib_1, n=2, test): R2=-1.3470, RMSE=23.9346
  Fold 2 (held out=DMSO_1, n=20, train): R2=0.8868, RMSE=14.5004
  Fold 2 (held out=DMSO_1, n=4, test): R2=0.0000, RMSE=29.3510
  Fold 3 (held out=Everolimus_1, n=23, train): R2=0.8947, RMSE=13.5221
  Fold 3 (held out=Everolimus_1, n=1, test): R2=nan, RMSE=12.7057

/home/lippincm/Documents/NF1_organoid_profile_analysis/.venv/lib/python3.13/site-packages/sklearn/metrics/_regression.py:1295: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)

  Fold 4 (held out=Fimepinostat_1, n=23, train): R2=0.8951, RMSE=13.5212
  Fold 4 (held out=Fimepinostat_1, n=1, test): R2=nan, RMSE=10.1298

/home/lippincm/Documents/NF1_organoid_profile_analysis/.venv/lib/python3.13/site-packages/sklearn/metrics/_regression.py:1295: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)

  Fold 5 (held out=Linsitinib_1, n=23, train): R2=0.8951, RMSE=13.5206
  Fold 5 (held out=Linsitinib_1, n=1, test): R2=nan, RMSE=0.2988

/home/lippincm/Documents/NF1_organoid_profile_analysis/.venv/lib/python3.13/site-packages/sklearn/metrics/_regression.py:1295: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)

  Fold 6 (held out=Mirdametinib_1, n=22, train): R2=0.8941, RMSE=13.8244
  Fold 6 (held out=Mirdametinib_1, n=2, test): R2=-3.4316, RMSE=13.9582
  Fold 7 (held out=Rapamycin_1, n=23, train): R2=0.8959, RMSE=13.2064
  Fold 7 (held out=Rapamycin_1, n=1, test): R2=nan, RMSE=39.0249

/home/lippincm/Documents/NF1_organoid_profile_analysis/.venv/lib/python3.13/site-packages/sklearn/metrics/_regression.py:1295: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)

  Fold 8 (held out=Selumetinib_1, n=23, train): R2=0.8941, RMSE=13.5207
  Fold 8 (held out=Selumetinib_1, n=1, test): R2=nan, RMSE=12.2577

/home/lippincm/Documents/NF1_organoid_profile_analysis/.venv/lib/python3.13/site-packages/sklearn/metrics/_regression.py:1295: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)

  Fold 9 (held out=Selumetinib_10, n=20, train): R2=0.9933, RMSE=3.1175
  Fold 9 (held out=Selumetinib_10, n=4, test): R2=-1.9337, RMSE=47.8066
  Fold 10 (held out=Staurosporine_10, n=19, train): R2=0.3772, RMSE=17.6181
  Fold 10 (held out=Staurosporine_10, n=5, test): R2=-11963.4892, RMSE=87.6164

--- loto summary (across 11 folds, test set) ---
               R2          MSE        MAE        MAPE       RMSE
mean -2008.210774  1237.182532  24.688914  162.063320  26.004583
std   4877.168815  2254.116381  24.446428  470.765718  24.840262
Any inf in X: False
Any NaN in X: False
Max abs value in X: 1.7037208758706792
Columns with inf values: []

=== random_split (70/30 train/test, n_train=16, n_test=8) for shuffled ===
  train (n=16): R2=0.5275, RMSE=28.9914
  test (n=8): R2=-0.1462, RMSE=40.1339

--- random_split summary (single split, test set) ---
            R2          MSE        MAE        MAPE       RMSE
mean -0.146215  1610.726781  29.714914  300.105738  40.133861
std        NaN          NaN        NaN         NaN        NaN
Processing and training model for sammed_sc_norm_sc_consensus_profiles...
Any inf in X: False
Any NaN in X: False
Max abs value in X: 1.658108115196228
Columns with inf values: []

=== lopo grouped CV on 'Metadata_Biology_PatientTumor' (6 folds) for not_shuffled ===
  Fold 0 (held out=NF0014_T1, n=21, train): R2=0.8758, RMSE=14.1499
  Fold 0 (held out=NF0014_T1, n=3, test): R2=-1.5966, RMSE=48.7293
  Fold 1 (held out=NF0014_T2, n=21, train): R2=0.8231, RMSE=17.6000
  Fold 1 (held out=NF0014_T2, n=3, test): R2=0.2977, RMSE=14.8380
  Fold 2 (held out=NF0018_T6, n=18, train): R2=0.8787, RMSE=15.2835
  Fold 2 (held out=NF0018_T6, n=6, test): R2=-0.5252, RMSE=36.3891
  Fold 3 (held out=NF0035_T1, n=19, train): R2=0.6319, RMSE=23.0843
  Fold 3 (held out=NF0035_T1, n=5, test): R2=0.2762, RMSE=41.3360
  Fold 4 (held out=NF0037_T1, n=19, train): R2=0.8730, RMSE=14.8774
  Fold 4 (held out=NF0037_T1, n=5, test): R2=0.2892, RMSE=31.1249
  Fold 5 (held out=NF0055_T1, n=22, train): R2=0.8783, RMSE=13.6152
  Fold 5 (held out=NF0055_T1, n=2, test): R2=-0.4420, RMSE=65.8239

--- lopo summary (across 6 folds, test set) ---
            R2          MSE        MAE        MAPE       RMSE
mean -0.283442  1821.513879  29.327371  298.941073  39.706855
std   0.746581  1425.758092  15.547766  392.634026  17.142212
Any inf in X: False
Any NaN in X: False
Max abs value in X: 1.658108115196228
Columns with inf values: []

=== loto grouped CV on 'Metadata_Experiment_FullTreatment' (11 folds) for not_shuffled ===
  Fold 0 (held out=Binimetinib_1, n=22, train): R2=0.8945, RMSE=13.8248
  Fold 0 (held out=Binimetinib_1, n=2, test): R2=-612.1785, RMSE=24.8147
  Fold 1 (held out=Copanlisib_1, n=22, train): R2=0.8926, RMSE=13.8245
  Fold 1 (held out=Copanlisib_1, n=2, test): R2=-4.7794, RMSE=37.5588
  Fold 2 (held out=DMSO_1, n=20, train): R2=0.8868, RMSE=14.5002
  Fold 2 (held out=DMSO_1, n=4, test): R2=0.0000, RMSE=9.3800
  Fold 3 (held out=Everolimus_1, n=23, train): R2=0.8947, RMSE=13.5216
  Fold 3 (held out=Everolimus_1, n=1, test): R2=nan, RMSE=40.6667

/home/lippincm/Documents/NF1_organoid_profile_analysis/.venv/lib/python3.13/site-packages/sklearn/metrics/_regression.py:1295: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)

  Fold 4 (held out=Fimepinostat_1, n=23, train): R2=0.8922, RMSE=13.7048
  Fold 4 (held out=Fimepinostat_1, n=1, test): R2=nan, RMSE=6.6233

/home/lippincm/Documents/NF1_organoid_profile_analysis/.venv/lib/python3.13/site-packages/sklearn/metrics/_regression.py:1295: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)

  Fold 5 (held out=Linsitinib_1, n=23, train): R2=0.8748, RMSE=14.7686
  Fold 5 (held out=Linsitinib_1, n=1, test): R2=nan, RMSE=68.7682

/home/lippincm/Documents/NF1_organoid_profile_analysis/.venv/lib/python3.13/site-packages/sklearn/metrics/_regression.py:1295: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)

  Fold 6 (held out=Mirdametinib_1, n=22, train): R2=0.8941, RMSE=13.8245
  Fold 6 (held out=Mirdametinib_1, n=2, test): R2=0.5943, RMSE=4.2235
  Fold 7 (held out=Rapamycin_1, n=23, train): R2=0.8959, RMSE=13.2064
  Fold 7 (held out=Rapamycin_1, n=1, test): R2=nan, RMSE=13.9088

/home/lippincm/Documents/NF1_organoid_profile_analysis/.venv/lib/python3.13/site-packages/sklearn/metrics/_regression.py:1295: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)

  Fold 8 (held out=Selumetinib_1, n=23, train): R2=0.8443, RMSE=16.3932
  Fold 8 (held out=Selumetinib_1, n=1, test): R2=nan, RMSE=12.7600

/home/lippincm/Documents/NF1_organoid_profile_analysis/.venv/lib/python3.13/site-packages/sklearn/metrics/_regression.py:1295: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)

  Fold 9 (held out=Selumetinib_10, n=20, train): R2=0.7079, RMSE=20.5568
  Fold 9 (held out=Selumetinib_10, n=4, test): R2=-1.7575, RMSE=46.3485
  Fold 10 (held out=Staurosporine_10, n=19, train): R2=0.5560, RMSE=14.8756
  Fold 10 (held out=Staurosporine_10, n=5, test): R2=-9556.0925, RMSE=78.3071

--- loto summary (across 11 folds, test set) ---
               R2          MSE        MAE        MAPE       RMSE
mean -1695.702256  1563.221170  29.332749  152.068879  31.214511
std   3858.529649  2070.700055  24.987571  413.072749  25.451189
Any inf in X: False
Any NaN in X: False
Max abs value in X: 1.658108115196228
Columns with inf values: []

=== random_split (70/30 train/test, n_train=16, n_test=8) for not_shuffled ===
  train (n=16): R2=0.8523, RMSE=16.2115
  test (n=8): R2=0.1155, RMSE=35.2558

--- random_split summary (single split, test set) ---
            R2         MSE        MAE        MAPE      RMSE
mean  0.115484  1242.97212  22.927798  255.288094  35.25581
std        NaN         NaN        NaN         NaN       NaN
Any inf in X: False
Any NaN in X: False
Max abs value in X: 1.658108115196228
Columns with inf values: []

=== lopo grouped CV on 'Metadata_Biology_PatientTumor' (6 folds) for shuffled ===
  Fold 0 (held out=NF0014_T1, n=21, train): R2=0.8758, RMSE=14.1520
  Fold 0 (held out=NF0014_T1, n=3, test): R2=-2.0671, RMSE=52.9601
  Fold 1 (held out=NF0014_T2, n=21, train): R2=0.8778, RMSE=14.6287
  Fold 1 (held out=NF0014_T2, n=3, test): R2=-5.8346, RMSE=46.2881
  Fold 2 (held out=NF0018_T6, n=18, train): R2=0.8565, RMSE=16.6249
  Fold 2 (held out=NF0018_T6, n=6, test): R2=-0.4274, RMSE=35.2037
  Fold 3 (held out=NF0035_T1, n=19, train): R2=0.2679, RMSE=32.5569
  Fold 3 (held out=NF0035_T1, n=5, test): R2=0.0823, RMSE=46.5460
  Fold 4 (held out=NF0037_T1, n=19, train): R2=0.8731, RMSE=14.8759
  Fold 4 (held out=NF0037_T1, n=5, test): R2=-0.1108, RMSE=38.9086
  Fold 5 (held out=NF0055_T1, n=22, train): R2=0.4961, RMSE=27.7053
  Fold 5 (held out=NF0055_T1, n=2, test): R2=-0.0032, RMSE=54.9036

--- lopo summary (across 6 folds, test set) ---
            R2          MSE        MAE        MAPE       RMSE
mean -1.393475  2146.912168  38.820999  342.555120  45.801675
std   2.318057   694.296239   7.873265  277.888634   7.677399
Any inf in X: False
Any NaN in X: False
Max abs value in X: 1.658108115196228
Columns with inf values: []

=== loto grouped CV on 'Metadata_Experiment_FullTreatment' (11 folds) for shuffled ===
  Fold 0 (held out=Binimetinib_1, n=22, train): R2=0.6791, RMSE=24.1110
  Fold 0 (held out=Binimetinib_1, n=2, test): R2=-94.0461, RMSE=9.7698
  Fold 1 (held out=Copanlisib_1, n=22, train): R2=0.8926, RMSE=13.8265
  Fold 1 (held out=Copanlisib_1, n=2, test): R2=-0.4152, RMSE=18.5856
  Fold 2 (held out=DMSO_1, n=20, train): R2=0.7465, RMSE=21.7044
  Fold 2 (held out=DMSO_1, n=4, test): R2=0.0000, RMSE=43.0237
  Fold 3 (held out=Everolimus_1, n=23, train): R2=0.3888, RMSE=32.5819
  Fold 3 (held out=Everolimus_1, n=1, test): R2=nan, RMSE=4.7239

/home/lippincm/Documents/NF1_organoid_profile_analysis/.venv/lib/python3.13/site-packages/sklearn/metrics/_regression.py:1295: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)

  Fold 4 (held out=Fimepinostat_1, n=23, train): R2=0.5569, RMSE=27.7838
  Fold 4 (held out=Fimepinostat_1, n=1, test): R2=nan, RMSE=6.3179

/home/lippincm/Documents/NF1_organoid_profile_analysis/.venv/lib/python3.13/site-packages/sklearn/metrics/_regression.py:1295: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)

  Fold 5 (held out=Linsitinib_1, n=23, train): R2=0.8950, RMSE=13.5280
  Fold 5 (held out=Linsitinib_1, n=1, test): R2=nan, RMSE=11.4243

/home/lippincm/Documents/NF1_organoid_profile_analysis/.venv/lib/python3.13/site-packages/sklearn/metrics/_regression.py:1295: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)

  Fold 6 (held out=Mirdametinib_1, n=22, train): R2=0.8209, RMSE=17.9764
  Fold 6 (held out=Mirdametinib_1, n=2, test): R2=-8.0910, RMSE=19.9919
  Fold 7 (held out=Rapamycin_1, n=23, train): R2=0.6915, RMSE=22.7361
  Fold 7 (held out=Rapamycin_1, n=1, test): R2=nan, RMSE=28.4451

/home/lippincm/Documents/NF1_organoid_profile_analysis/.venv/lib/python3.13/site-packages/sklearn/metrics/_regression.py:1295: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)

  Fold 8 (held out=Selumetinib_1, n=23, train): R2=0.5744, RMSE=27.1014

/home/lippincm/Documents/NF1_organoid_profile_analysis/.venv/lib/python3.13/site-packages/sklearn/metrics/_regression.py:1295: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)

  Fold 8 (held out=Selumetinib_1, n=1, test): R2=nan, RMSE=29.4356
  Fold 9 (held out=Selumetinib_10, n=20, train): R2=0.0000, RMSE=38.0361
  Fold 9 (held out=Selumetinib_10, n=4, test): R2=-3.0980, RMSE=56.5029
  Fold 10 (held out=Staurosporine_10, n=19, train): R2=0.3486, RMSE=18.0180
  Fold 10 (held out=Staurosporine_10, n=5, test): R2=-11673.1301, RMSE=86.5467

--- loto summary (across 11 folds, test set) ---
               R2          MSE        MAE        MAPE       RMSE
mean -1963.130078  1385.710572  27.232668  162.678245  28.615223
std   4757.049695  2243.088256  24.363453  464.959654  24.971335
Any inf in X: False
Any NaN in X: False
Max abs value in X: 1.658108115196228
Columns with inf values: []

=== random_split (70/30 train/test, n_train=16, n_test=8) for shuffled ===
  train (n=16): R2=0.8522, RMSE=16.2121
  test (n=8): R2=-0.0478, RMSE=38.3728

--- random_split summary (single split, test set) ---
            R2          MSE        MAE        MAPE       RMSE
mean -0.047829  1472.469641  26.514851  292.281391  38.372772
std        NaN          NaN        NaN         NaN        NaN

In [8]:
results

{'profile_type': ['nucleocentric_morphem_norm_sc_consensus_profiles',
  'nucleocentric_morphem_norm_sc_consensus_profiles',
  'nucleocentric_morphem_norm_sc_consensus_profiles',
  'nucleocentric_morphem_norm_sc_consensus_profiles',
  'nucleocentric_morphem_norm_sc_consensus_profiles',
  'nucleocentric_morphem_norm_sc_consensus_profiles',
  'sammed_organoid_norm_sc_consensus_profiles',
  'sammed_organoid_norm_sc_consensus_profiles',
  'sammed_organoid_norm_sc_consensus_profiles',
  'sammed_organoid_norm_sc_consensus_profiles',
  'sammed_organoid_norm_sc_consensus_profiles',
  'sammed_organoid_norm_sc_consensus_profiles',
  'sc_norm_sc_consensus_profiles',
  'sc_norm_sc_consensus_profiles',
  'sc_norm_sc_consensus_profiles',
  'sc_norm_sc_consensus_profiles',
  'sc_norm_sc_consensus_profiles',
  'sc_norm_sc_consensus_profiles',
  'organoid_norm_sc_consensus_profiles',
  'organoid_norm_sc_consensus_profiles',
  'organoid_norm_sc_consensus_profiles',
  'organoid_norm_sc_consensus_profiles',
  'organoid_norm_sc_consensus_profiles',
  'organoid_norm_sc_consensus_profiles',
  'sammed_nucleocentric_norm_sc_consensus_profiles',
  'sammed_nucleocentric_norm_sc_consensus_profiles',
  'sammed_nucleocentric_norm_sc_consensus_profiles',
  'sammed_nucleocentric_norm_sc_consensus_profiles',
  'sammed_nucleocentric_norm_sc_consensus_profiles',
  'sammed_nucleocentric_norm_sc_consensus_profiles',
  'sammed_sc_norm_sc_consensus_profiles',
  'sammed_sc_norm_sc_consensus_profiles',
  'sammed_sc_norm_sc_consensus_profiles',
  'sammed_sc_norm_sc_consensus_profiles',
  'sammed_sc_norm_sc_consensus_profiles',
  'sammed_sc_norm_sc_consensus_profiles'],
 'split_method': ['lopo',
  'loto',
  'random_split',
  'lopo',
  'loto',
  'random_split',
  'lopo',
  'loto',
  'random_split',
  'lopo',
  'loto',
  'random_split',
  'lopo',
  'loto',
  'random_split',
  'lopo',
  'loto',
  'random_split',
  'lopo',
  'loto',
  'random_split',
  'lopo',
  'loto',
  'random_split',
  'lopo',
  'loto',
  'random_split',
  'lopo',
  'loto',
  'random_split',
  'lopo',
  'loto',
  'random_split',
  'lopo',
  'loto',
  'random_split'],
 'shuffle_status': ['not_shuffled',
  'not_shuffled',
  'not_shuffled',
  'shuffled',
  'shuffled',
  'shuffled',
  'not_shuffled',
  'not_shuffled',
  'not_shuffled',
  'shuffled',
  'shuffled',
  'shuffled',
  'not_shuffled',
  'not_shuffled',
  'not_shuffled',
  'shuffled',
  'shuffled',
  'shuffled',
  'not_shuffled',
  'not_shuffled',
  'not_shuffled',
  'shuffled',
  'shuffled',
  'shuffled',
  'not_shuffled',
  'not_shuffled',
  'not_shuffled',
  'shuffled',
  'shuffled',
  'shuffled',
  'not_shuffled',
  'not_shuffled',
  'not_shuffled',
  'shuffled',
  'shuffled',
  'shuffled'],
 'results': [    Metadata_fold Metadata_held_out_group Metadata_eval_split  \
  0               0               NF0014_T1               train
  1               0               NF0014_T1                test
  2               1               NF0014_T2               train
  3               1               NF0014_T2                test
  4               2               NF0018_T6               train
  5               2               NF0018_T6                test
  6               3               NF0035_T1               train
  7               3               NF0035_T1                test
  8               4               NF0037_T1               train
  9               4               NF0037_T1                test
  10              5               NF0055_T1               train
  11              5               NF0055_T1                test

      Metadata_n_samples        R2          MSE        MAE         MAPE  \
  0                   21  0.839969   258.031959  10.079902    58.822515
  1                    3  0.602899   363.136986  13.227461   199.184923
  2                   21  0.872651   223.034755   8.802175    53.344714
  3                    3 -4.377301  1685.727070  31.993991    29.497343
  4                   18  0.847732   293.228071  10.709097    59.589648
  5                    6  0.169259   721.241990  20.232803   130.100396
  6                   19  0.740695   375.436822  14.976454   135.222176
  7                    5  0.442806  1315.428104  25.908251   117.133660
  8                   19  0.821271   311.564300  11.576865    76.318060
  9                    5  0.942573    78.268649   7.254841    56.586612
  10                  22  0.871702   195.450133   6.127424    17.866040
  11                   2 -0.556910  4678.208009  54.816080  1125.246795

           RMSE
  0   16.063373
  1   19.056153
  2   14.934348
  3   41.057607
  4   17.123904
  5   26.855949
  6   19.376192
  7   36.268831
  8   17.651184
  9    8.846957
  10  13.980348
  11  68.397427  ,
      Metadata_fold Metadata_held_out_group Metadata_eval_split  \
  0               0           Binimetinib_1               train
  1               0           Binimetinib_1                test
  2               1            Copanlisib_1               train
  3               1            Copanlisib_1                test
  4               2                  DMSO_1               train
  5               2                  DMSO_1                test
  6               3            Everolimus_1               train
  7               3            Everolimus_1                test
  8               4          Fimepinostat_1               train
  9               4          Fimepinostat_1                test
  10              5            Linsitinib_1               train
  11              5            Linsitinib_1                test
  12              6          Mirdametinib_1               train
  13              6          Mirdametinib_1                test
  14              7             Rapamycin_1               train
  15              7             Rapamycin_1                test
  16              8           Selumetinib_1               train
  17              8           Selumetinib_1                test
  18              9          Selumetinib_10               train
  19              9          Selumetinib_10                test
  20             10        Staurosporine_10               train
  21             10        Staurosporine_10                test

      Metadata_n_samples           R2          MSE        MAE         MAPE  \
  0                   22     0.819103   327.691998  12.286361    90.881151
  1                    2   -61.885154    63.151062   7.893756     9.213661
  2                   22     0.725322   488.702680  15.311887   140.025931
  3                    2    -0.393662   340.173648  17.160236    33.368476
  4                   20     0.770717   426.045293  14.516419   120.518701
  5                    4     0.000000    92.011654   9.592271     9.592271
  6                   23     0.827296   299.986068  11.583312    80.380337
  7                    1          NaN   958.404392  30.958107    35.550250
  8                   23     0.865742   233.903340   9.071350    50.972061
  9                    1          NaN  3385.803227  58.187655    82.748717
  10                  23     0.752153   431.873035  14.499175   120.825029
  11                   1          NaN   305.299602  17.472825    21.969765
  12                  22     0.804483   352.708473  13.085121   100.406452
  13                   2     0.046555    41.917461   6.455521     7.471374
  14                  23     0.715180   477.250408  15.333739   134.142142
  15                   1          NaN   193.454768  13.908802    12.210472
  16                  23     0.802773   340.339877  12.682703    96.084401
  17                   1          NaN    24.738905   4.973822     5.234160
  18                  20     0.881830   170.961970  10.325895    93.567720
  19                   4    -1.561401  1995.454420  34.895539    26.170866
  20                  19     0.555455   221.554234   5.410540     4.023890
  21                   5 -9605.396177  6163.632308  77.644141  1432.062144

           RMSE
  0   18.102265
  1    7.946764
  2   22.106621
  3   18.443797
  4   20.640865
  5    9.592271
  6   17.320106
  7   30.958107
  8   15.293899
  9   58.187655
  10  20.781555
  11  17.472825
  12  18.780534
  13   6.474370
  14  21.846062
  15  13.908802
  16  18.448303
  17   4.973822
  18  13.075243
  19  44.670510
  20  14.884698
  21  78.508804  ,
     Metadata_fold Metadata_held_out_group Metadata_eval_split  \
  0              0    random_30pct_holdout               train
  1              0    random_30pct_holdout                test

     Metadata_n_samples        R2         MSE        MAE        MAPE       RMSE
  0                  16  0.852225  262.860038   6.228618    5.690405  16.212959
  1                   8  0.439592  787.517887  18.216818  101.564711  28.062749  ,
      Metadata_fold Metadata_held_out_group Metadata_eval_split  \
  0               0               NF0014_T1               train
  1               0               NF0014_T1                test
  2               1               NF0014_T2               train
  3               1               NF0014_T2                test
  4               2               NF0018_T6               train
  5               2               NF0018_T6                test
  6               3               NF0035_T1               train
  7               3               NF0035_T1                test
  8               4               NF0037_T1               train
  9               4               NF0037_T1                test
  10              5               NF0055_T1               train
  11              5               NF0055_T1                test

      Metadata_n_samples        R2          MSE        MAE        MAPE  \
  0                   21  0.016318  1586.072111  29.228977  267.949384
  1                    3 -1.478561  2266.571321  36.720132  477.166749
  2                   21  0.000000  1751.371580  34.003291  303.487946
  3                    3 -2.888506  1219.005498  30.091794   27.430159
  4                   18  0.878286   234.388139   6.025389   11.174406
  5                    6 -0.424982  1237.156878  21.073480  224.606982
  6                   19  0.026107  1410.056771  30.738229  270.162255
  7                    5 -0.089506  2572.115755  40.940659  266.139098
  8                   19  0.000000  1743.217611  32.285387  290.442419
  9                    5 -0.029760  1403.473277  33.315089  224.569783
  10                  22  0.000000  1523.403526  29.241164  233.119144
  11                   2 -0.103792  3316.676257  54.816080  863.656921

           RMSE
  0   39.825521
  1   47.608522
  2   41.849392
  3   34.914259
  4   15.309740
  5   35.173241
  6   37.550723
  7   50.716031
  8   41.751858
  9   37.462959
  10  39.030802
  11  57.590592  ,
      Metadata_fold Metadata_held_out_group Metadata_eval_split  \
  0               0           Binimetinib_1               train
  1               0           Binimetinib_1                test
  2               1            Copanlisib_1               train
  3               1            Copanlisib_1                test
  4               2                  DMSO_1               train
  5               2                  DMSO_1                test
  6               3            Everolimus_1               train
  7               3            Everolimus_1                test
  8               4          Fimepinostat_1               train
  9               4          Fimepinostat_1                test
  10              5            Linsitinib_1               train
  11              5            Linsitinib_1                test
  12              6          Mirdametinib_1               train
  13              6          Mirdametinib_1                test
  14              7             Rapamycin_1               train
  15              7             Rapamycin_1                test
  16              8           Selumetinib_1               train
  17              8           Selumetinib_1                test
  18              9          Selumetinib_10               train
  19              9          Selumetinib_10                test
  20             10        Staurosporine_10               train
  21             10        Staurosporine_10                test

      Metadata_n_samples            R2          MSE        MAE         MAPE  \
  0                   22      0.000000  1811.487214  34.242680   301.944207
  1                    2   -131.185635   132.744578  11.477820    13.365230
  2                   22      0.000000  1779.187071  32.827176   307.915730
  3                    2     -1.041279   498.247941  15.942453    35.248079
  4                   20      0.000000  1858.165661  34.875828   312.334899
  5                    4      0.000000   879.881378  29.662795    29.662795
  6                   23      0.000000  1736.996356  33.023745   290.833995
  7                    1           NaN   151.653862  12.314782    14.141484
  8                   23      0.000000  1742.197998  33.017125   293.546016
  9                    1           NaN    26.814451   5.178267     7.364018
  10                  23      0.000000  1742.495709  33.223594   292.295285
  11                   1           NaN    19.669387   4.435018     5.576449
  12                  22      0.000000  1803.976216  34.149814   301.321992
  13                   2     -3.980665   218.971105  13.229016    14.643682
  14                  23      0.000000  1675.620444  32.313791   286.042083
  15                   1           NaN  1624.675746  40.307267    35.385559
  16                  23      0.000000  1725.627318  32.813520   289.360710
  17                   1           NaN   424.510774  20.603659    21.682088
  18                  20      0.000000  1446.748669  32.927472   298.535535
  19                   4     -3.098045  3192.573730  49.127648    39.086956
  20                  19      0.001620   497.576704  15.061679    17.846055
  21                   5 -12061.070482  7739.236021  87.969240  1595.403832

           RMSE
  0   42.561570
  1   11.521483
  2   42.180411
  3   22.321468
  4   43.106446
  5   29.662795
  6   41.677288
  7   12.314782
  8   41.739645
  9    5.178267
  10  41.743212
  11   4.435018
  12  42.473241
  13  14.797672
  14  40.934343
  15  40.307267
  16  41.540671
  17  20.603659
  18  38.036150
  19  56.502865
  20  22.306427
  21  87.972928  ,
     Metadata_fold Metadata_held_out_group Metadata_eval_split  \
  0              0    random_30pct_holdout               train
  1              0    random_30pct_holdout                test

     Metadata_n_samples        R2          MSE        MAE        MAPE       RMSE
  0                  16  0.852232   262.846970   6.209711    6.471683  16.212556
  1                   8 -0.119703  1573.470541  29.012365  294.519036  39.666996  ,
      Metadata_fold Metadata_held_out_group Metadata_eval_split  \
  0               0               NF0014_T1               train
  1               0               NF0014_T1                test
  2               1               NF0014_T2               train
  3               1               NF0014_T2                test
  4               2               NF0018_T6               train
  5               2               NF0018_T6                test
  6               3               NF0035_T1               train
  7               3               NF0035_T1                test
  8               4               NF0037_T1               train
  9               4               NF0037_T1                test
  10              5               NF0055_T1               train
  11              5               NF0055_T1                test

      Metadata_n_samples        R2          MSE        MAE        MAPE  \
  0                   21  0.875826   200.216572   4.655287    3.828442
  1                    3 -0.876520  1716.022192  38.921324  299.090406
  2                   21  0.849506   263.571193  10.296667   72.644213
  3                    3 -2.255097  1020.438548  26.489799   24.415293
  4                   18  0.878701   233.589470   5.433511    4.577114
  5                    6 -1.468663  2143.271432  33.098652   47.067901
  6                   19  0.968017    46.306265   3.432517   18.485628
  7                    5  0.519683  1133.936724  25.924686  173.023183
  8                   19  0.873052   221.297379   5.147042    4.406429
  9                    5  0.766717   317.944335  15.089986  102.431609
  10                  22  0.792173   316.604600  11.318203   76.015022
  11                   2  0.362957  1914.187817  39.273486  693.367538

           RMSE
  0   14.149791
  1   41.424898
  2   16.234876
  3   31.944304
  4   15.283634
  5   46.295480
  6    6.804871
  7   33.673977
  8   14.876067
  9   17.830994
  10  17.793386
  11  43.751432  ,
      Metadata_fold Metadata_held_out_group Metadata_eval_split  \
  0               0           Binimetinib_1               train
  1               0           Binimetinib_1                test
  2               1            Copanlisib_1               train
  3               1            Copanlisib_1                test
  4               2                  DMSO_1               train
  5               2                  DMSO_1                test
  6               3            Everolimus_1               train
  7               3            Everolimus_1                test
  8               4          Fimepinostat_1               train
  9               4          Fimepinostat_1                test
  10              5            Linsitinib_1               train
  11              5            Linsitinib_1                test
  12              6          Mirdametinib_1               train
  13              6          Mirdametinib_1                test
  14              7             Rapamycin_1               train
  15              7             Rapamycin_1                test
  16              8           Selumetinib_1               train
  17              8           Selumetinib_1                test
  18              9          Selumetinib_10               train
  19              9          Selumetinib_10                test
  20             10        Staurosporine_10               train
  21             10        Staurosporine_10                test

      Metadata_n_samples           R2          MSE        MAE         MAPE  \
  0                   22     0.894491   191.127830   4.476283     4.018035
  1                    2 -3072.727160  3086.724324  45.325433    53.270019
  2                   22     0.891243   193.499864   5.474862    13.414766
  3                    2    -6.338246  1791.163995  39.332911    76.542079
  4                   20     0.886861   210.231047   4.894534     4.164032
  5                    4     0.000000   137.220438  10.616695    10.616695
  6                   23     0.894616   183.050902   4.539319     6.011607
  7                    1          NaN   580.163545  24.086584    27.659446
  8                   23     0.895070   182.809227   4.256791     3.593119
  9                    1          NaN  4944.691233  70.318499   100.000000
  10                  23     0.892912   186.600705   5.430816    15.922289
  11                   1          NaN   104.334411  10.214422    12.843284
  12                  22     0.890495   197.545090   5.929238    20.296915
  13                   2    -4.241756   230.449772  13.293002    15.936008
  14                  23     0.834347   277.571763  10.760237    78.271838
  15                   1          NaN   333.684717  18.267039    16.036547
  16                  23     0.888575   192.277498   6.251429    24.084590
  17                   1          NaN    24.738905   4.973822     5.234160
  18                  20     0.987733    17.746637   2.837649    16.849583
  19                   4    -4.764723  4490.995408  65.974327    61.884429
  20                  19     0.555865   221.349844   5.273151     3.842344
  21                   5 -9597.242269  6158.400617  76.856420  1417.085564

           RMSE
  0   13.824899
  1   55.558297
  2   13.910423

In [9]:
pd.read_parquet(
    pathlib.Path(
        "../model_results/lopo_predicted_viabilities__not_shuffled__sammed_nucleocentric_norm_sc_consensus_profiles.parquet"
    )
)

,Metadata_Biology_PatientTumor,Metadata_Experiment_Treatment,Metadata_Experiment_Dose,Metadata_Experiment_Class,Metadata_Experiment_Target,Metadata_Experiment_TherapeuticCategories,Metadata_Experiment_Unit,Nucleocentric_AGP_SAMMed3D_Feature0,Nucleocentric_AGP_SAMMed3D_Feature1,Nucleocentric_AGP_SAMMed3D_Feature10,...,Nucleocentric_Mito_SAMMed3D_Feature96,Nucleocentric_Mito_SAMMed3D_Feature97,Nucleocentric_Mito_SAMMed3D_Feature98,Nucleocentric_Mito_SAMMed3D_Feature99,Viability_percentage,Metadata_Experiment_FullTreatment,Actual_Viability,Predicted_Viability,Metadata_fold,Metadata_held_out_group
0,NF0014_T1,Staurosporine,10,Small Molecule,Apoptosis induction,Experimental,nM,-0.449589,-1.113767,0.714894,...,-0.834729,0.458213,-0.073315,0.375830,5.515339,Staurosporine_10,5.515339,69.596322,0,NF0014_T1
1,NF0014_T1,Linsitinib,1,Small Molecule,IGF-1R inhibitor,Investigational,uM,-0.050384,-0.244386,0.241700,...,0.080646,-0.064007,-0.275601,-0.053719,79.531230,Linsitinib_1,79.531230,97.499435,0,NF0014_T1
2,NF0014_T1,Copanlisib,1,Small Molecule,PI3K inhibitor,Kinase Inhibitor,uM,-0.291448,-0.651557,0.344767,...,-0.007808,0.308240,-0.389865,0.000395,45.043833,Copanlisib_1,45.043833,61.067996,0,NF0014_T1
3,NF0014_T2,Mirdametinib,1,Small Molecule,MEK1/2 inhibitor,Kinase Inhibitor,uM,-0.094685,-0.382230,0.341613,...,-0.276874,0.700693,0.092751,0.330359,80.777050,Mirdametinib_1,80.777050,28.128755,1,NF0014_T2
4,NF0014_T2,Selumetinib,10,Small Molecule,MEK1/2 inhibitor,Kinase Inhibitor,uM,-0.017732,-0.005597,-0.406061,...,-0.006818,0.283831,0.073561,0.095566,124.056923,Selumetinib_10,124.056923,66.138986,1,NF0014_T2
5,NF0014_T2,DMSO,1,Control,Control,Control,%,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,100.000000,DMSO_1,100.000000,93.251278,1,NF0014_T2
6,NF0018_T6,Copanlisib,1,Small Molecule,PI3K inhibitor,Kinase Inhibitor,uM,0.147950,-0.199917,0.198630,...,0.009871,-0.002281,-0.126648,0.248119,76.290346,Copanlisib_1,76.290346,50.326766,2,NF0018_T6
7,NF0018_T6,Fimepinostat,1,Small Molecule,PI3K and HDAC inhibitor,Investigational,uM,-0.025592,-0.546546,0.511470,...,-0.326295,0.421039,-0.180315,-0.165073,70.318499,Fimepinostat_1,70.318499,22.901508,2,NF0018_T6
8,NF0018_T6,Selumetinib,10,Small Molecule,MEK1/2 inhibitor,Kinase Inhibitor,uM,-0.230507,-0.254793,0.398020,...,0.100643,0.180156,-0.087472,-0.136363,91.120432,Selumetinib_10,91.120432,77.834896,2,NF0018_T6
9,NF0018_T6,Binimetinib,1,Small Molecule,MEK1/2 inhibitor,Kinase Inhibitor,uM,0.017104,-0.178551,0.147404,...,0.204087,0.012286,0.008969,-0.191729,84.800228,Binimetinib_1,84.800228,76.504424,2,NF0018_T6
10,NF0018_T6,Selumetinib,10,Small Molecule,MEK1/2 inhibitor,Kinase Inhibitor,uM,-0.230507,-0.254793,0.398020,...,0.100643,0.180156,-0.087472,-0.136363,91.120432,Selumetinib_10,91.120432,77.834896,2,NF0018_T6
11,NF0018_T6,Staurosporine,10,Small Molecule,Apoptosis induction,Experimental,nM,0.060178,-0.249311,0.358064,...,-0.342963,0.282387,-0.045826,0.107670,6.295322,Staurosporine_10,6.295322,51.427211,2,NF0018_T6
12,NF0035_T1,Staurosporine,10,Small Molecule,Apoptosis induction,Experimental,nM,-0.223111,-0.609389,0.596794,...,-0.400159,0.290030,0.059007,-0.121444,5.564388,Staurosporine_10,5.564388,23.732097,3,NF0035_T1
13,NF0035_T1,Selumetinib,10,Small Molecule,MEK1/2 inhibitor,Kinase Inhibitor,uM,0.062892,-0.030788,-0.109029,...,-0.143238,0.083487,-0.024426,0.072201,158.585056,Selumetinib_10,158.585056,97.617196,3,NF0035_T1
14,NF0035_T1,Everolimus,1,Small Molecule,mTOR inhibitor,Kinase Inhibitor,uM,-0.223505,-0.341234,0.330606,...,-0.106491,0.132105,0.002460,0.026633,87.082671,Everolimus_1,87.082671,57.385140,3,NF0035_T1
15,NF0035_T1,Mirdametinib,1,Small Molecule,MEK1/2 inhibitor,Kinase Inhibitor,uM,-0.021993,0.021250,-0.279856,...,-0.074103,-0.101548,0.007869,-0.039364,94.038156,Mirdametinib_1,94.038156,98.187553,3,NF0035_T1
16,NF0035_T1,Binimetinib,1,Small Molecule,MEK1/2 inhibitor,Kinase Inhibitor,uM,-0.330227,-0.200505,0.312352,...,0.020747,0.092920,0.049746,0.036689,86.804452,Binimetinib_1,86.804452,78.841025,3,NF0035_T1
17,NF0037_T1,DMSO,1,Control,Control,Control,%,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,100.000000,DMSO_1,100.000000,99.891398,4,NF0037_T1
18,NF0037_T1,DMSO,1,Control,Control,Control,%,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,100.000000,DMSO_1,100.000000,99.891398,4,NF0037_T1
19,NF0037_T1,Staurosporine,10,Small Molecule,Apoptosis induction,Experimental,nM,-0.044500,-0.510914,0.596369,...,-0.073787,0.172365,0.032419,-0.148904,6.588133,Staurosporine_10,6.588133,7.493285,4,NF0037_T1
20,NF0037_T1,DMSO,1,Control,Control,Control,%,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,100.000000,DMSO_1,100.000000,99.891398,4,NF0037_T1
21,NF0037_T1,Selumetinib,1,Small Molecule,MEK1/2 inhibitor,Kinase Inhibitor,uM,-0.070179,-0.026236,0.052934,...,-0.099217,0.120100,-0.145283,0.174650,95.026178,Selumetinib_1,95.026178,89.877359,4,NF0037_T1
22,NF0055_T1,Rapamycin,1,Small Molecule,mTOR inhibitor,Kinase Inhibitor,uM,0.062646,0.303076,-0.291113,...,0.053246,0.131066,0.127361,0.000067,113.908802,Rapamycin_1,113.908802,100.000000,5,NF0055_T1
23,NF0055_T1,Staurosporine,10,Small Molecule,Apoptosis induction,Experimental,nM,0.303523,-0.156299,0.252488,...,0.131110,0.158879,0.237679,-0.240862,4.276642,Staurosporine_10,4.276642,72.433943,5,NF0055_T1